### ISSUE TITLE
lwM2M 

### ISSUE THREAD

**Issue by Koenma413** [chrysn/aiocoap#100]
lwM2M, client support CON，GET。
aiocoap client how to get the server (CON, GET) from  when the client is registered with the server?

**Comment by chrysn** [comment]
Sorry, I have no clue as to what you mean by that question. Can you re-phrase it, elaborate or share code of what you are trying to do?

**Comment by Koenma413** [comment]
### lwM2M client
The lwM2M client sends the register message to the server,below:
lwM2M client ---> lwM2M server  （register message，CON POST）
Then wait for the server to send a Observe to the client，below：
lwM2M client <--- lwM2M server   ( Observe message,  CON GET)
lwM2M client ---> lwM2M server   ( Observe ack message,  NON ACK )
lwM2M client ---> lwM2M server   ( Notify message,     NON POST )

These are simple process interactions, aiocoap when the Observe message is received, the judgment is the request message, and after the judgment is not the content of the server, it is not processed, and the message received is not sent 
```
dispatch_message  
elif message.code.is_request() and message.mtype in (CON, NON):
```
What should I do?

**Comment by Koenma413** [comment]
###lwM2M client

The lwM2M client sends the register message to the server,below:
```
lwM2M client ---> lwM2M server （register message，CON POST）
lwM2M client ---> lwM2M server  ( register ack message, NON ACK )
```

Then wait for the server to send a Observe to the client，below：
```
lwM2M client <--- lwM2M server ( Observe message, CON GET)
lwM2M client ---> lwM2M server ( Observe ack message, NON ACK )
lwM2M client ---> lwM2M server ( Notify message, NON POST )
```

These are simple process interactions, aiocoap when the Observe message is received, the judgment is the request message, and after the judgment is not the content of the server, it is not processed, and the message received is not sent

dispatch_message  
elif message.code.is_request() and message.mtype in (CON, NON):
What should I do?

**Comment by chrysn** [comment]
You definitely don't need to write code decides whether the message is a request here, that is what you're using a CoAP library for.

If lwm2m requires you to act both as a CoAP client and a CoAP server, you should really have the server part running all the time and not only look for requests after you registered that come from the lwM2M server after you registered -- everything else would be abusing the architecture.

To run a server, create the context as in the `server.py` example. You can use the context created by `create_server_context` to do your client operations too, just replace your `create_client_context` with `create_server_context` and supply it with a site that contains what you need to have available for the observations.

**Comment by Koenma413** [comment]
Thank you very much. I'll try
