### ISSUE TITLE
The transport can not be bound to any-address.

### ISSUE THREAD

**Issue by wangnuannuan** [chrysn/aiocoap#101]
I run the server.py in windows , but

ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Context.create_server_context() done, defined at F:\pr\python\aiocoap-master\aiocoap\protocol.py:545> exception=ValueError('The transport can not be bound to any-address.',)>
Traceback (most recent call last):
  File "F:\pr\python\aiocoap-master\aiocoap\protocol.py", line 576, in create_server_context
    self.transport_endpoints.append(await TransportEndpointSimpleServer.create_server(bind, self, log=self.log, loop=loop))
  File "F:\pr\python\aiocoap-master\aiocoap\transports\simplesocketserver.py", line 113, in create_server
    self._pool = await _DatagramServerSocketSimple.create(server_address, log, self._loop, self._received_datagram, self._received_exception)
  File "F:\pr\python\aiocoap-master\aiocoap\transports\simplesocketserver.py", line 59, in create
    raise ValueError("The transport can not be bound to any-address.")
ValueError: The transport can not be bound to any-address.

**Comment by chrysn** [comment]
That is to be expected and a known limitation of CoAP under Windows.

If you want to run a server, you need to explicitly give an IP address you want to serve from. [This is only described but not detailed in the documentation](http://aiocoap.readthedocs.io/en/latest/module/aiocoap.transports.simplesocketserver.html): The background is that Windows (or Python on Windows, can't tell) does not support the RECVPKTINFO socket option which would tell the server which of its addresses the incoming package was sent to, which is needed to form an appropriate response.

You'll need to set the `bind` parameter to some address or name, typically the IPv6 address of your server. Is that a viable approach in your application?

**Comment by chrysn** [comment]
Closing as no further input arrived, and because the FAQ now contains an explicit entry on this. (The solution is still to pick an own IP address).

**Comment by Adilius** [comment]
For anyone in the future having similar issue.

With the line: `await aiocoap.Context.create_server_context(site=root)`
Giving the error: `ValueError: The transport can not be bound to any-address.`

Through following the FaQ's and documentation, you need to specify a value to the bind parameter with a tuple of IP and port. As such: `await aiocoap.Context.create_server_context(bind=('127.0.0.1',5683),site=root)`

**Comment by jaimejim** [comment]
Funny, I arrived here by googling _ValueError: The transport can not be bound to any-address._ This page the first result 😄

Anyways, I confirm that `await aiocoap.Context.create_server_context(bind=('127.0.0.1',5683),site=root)`  solves it for me on Apple Mac too.

**Comment by chrysn** [comment]
It's essentially all OSes on which the udp6 transport is not default.

Given that MacOS should have all the properties needed (except Linux's RECVERR, which is a great enhancement when it comes to error handling), it might be worth revisiting that statement. To gather some data, could you try running aiocoap with AIOCOAP_SERVER_TRANSPORT=udp6 (or "udp6:" followed by whatever your `python3 -m aiocoap.cli.defaults` default server transports are, if you need more)?

**Comment by jaimejim** [comment]
Sure!

```
❯ AIOCOAP_SERVER_TRANSPORT=udp6 python3 -m aiocoap.cli.defaults
Python version: 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)]
aiocoap version: 0.4.4.post0
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: missing cryptography, filelock, ge25519
    linkheader: everything there
    prettyprint: missing termcolor, pygments
Python platform: darwin
Default server transports:  tcpserver:tcpclient:tlsserver:tlsclient:simple6:simplesocketserver
Selected server transports: udp6
Default client transports:  tcpclient:tlsclient:simple6
Selected client transports: tcpclient:tlsclient:simple6
SO_REUSEPORT available (default, selected): True, True
```
