### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by antoniosap** [chrysn/aiocoap#110]
```
File "/home/antonio/anaconda3/envs/myHome-hass-io/lib/python3.6/site-packages/aiocoap-0.4a1-py3.6.egg/aiocoap/resourcedirectory/client/register.py", line 262
    await asyncio.sleep(2 * 3 ** (i - 1)) # arbitrary fall-off
                ^
SyntaxError: invalid syntax

```

after 

pip install asyncio

**Comment by chrysn** [comment]
Could you verify that you are running a supported version of Python (ie. 3.5 or greater)?

**Comment by antoniosap** [comment]
yes

Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) 
[GCC 7.2.0] on linux
>>>

**Comment by chrysn** [comment]
That's a bit odd at various points -- line 262 of the respective file in 0.4a1 as from pypi should be `if try_reuse_discovery`, and the `await asyncio.sleep` line was only introduced 2017-11-22, a week after 0.4a1. Installing asyncio via pip should probably not do anything any more on a Python 3.4 or newer, as asyncio is built in there.

How did you install aiocoap? Which full program were you running, can you add a complete backtrace?

**Comment by chrysn** [comment]
Ah, found the culprit; sorry, I was only looking in the released and not the development version (which, of course, when locally pip-installed, would show as 0.4a1 just as well).

Thanks for reporting this, a fix is being uploaded.
