### ISSUE TITLE
Should OSError be wrapped?

### ISSUE THREAD

**Issue by balloob** [chrysn/aiocoap#124]
Getting a response from an IKEA Gateway can trigger an OS Errror. Since aiocoap has their own errors, should we catch OSError and wrap it?

Relevant lines from a stacktrace from issue https://github.com/home-assistant/home-assistant/issues/17008

```
  File "/usr/local/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 92, in _get_response
    r = yield from pr.response
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 816, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 865, in _run
    blockresponse = yield from blockrequest.response
OSError: [Errno -1] No error information
```

**Comment by chrysn** [comment]
On Tue, Oct 02, 2018 at 02:00:36AM -0700, Paulus Schoutsen wrote:
> Getting a response from an IKEA Gateway can trigger an OS Errror.
> Since aiocoap has their own errors, should we catch OSError and wrap
> it?

Yes it should.

Off my head I think that it only throws OSError and socket.gaierror, so
you can catch those two as a workaround until the errors thrown are made
to fit the rest of the transport design.

**Comment by chrysn** [comment]
@balloob, I've started working on wrapping the low-level errors, but it'll be some time until I'm confident enough that I'm catching all to close this issue.

When you next update the aiocoap version used in pytradfri, you will want to catch `aiocoap.error.NetworkError` as well, as the new errors can't practically derive from the ones you catch so far.

**Comment by balloob** [comment]
Ok!

**Comment by chrysn** [comment]
I haven't seen any errors that should be `aiocoap.error.NetworkError` in quite some time. Closing this, please report any errors that should be NetworkError (in general any OSError, gaierror or other socket error) that are raised out of aiocoap in a separate issue.
