### ISSUE TITLE
aiocoap on Home Assistant without IPv6 enabled

### ISSUE THREAD

**Issue by suppnet** [chrysn/aiocoap#129]
Hello,

So I'm trying to add IKEA Tradfri gateway using HA web interface. But it seems that something need to have IPv6 enabled, which is not and I would prefer not to change this.

Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/aiocoap/protocol.py", line 528, in create_client_context
Nov 11 15:15:10 odroid2 hass[5423]:     self.transport_endpoints.append((yield from TransportEndpointUDP6.create_client_transport_endpoint(new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop, dump_to=dump_to)))
Nov 11 15:15:10 odroid2 hass[5423]:   File "/home/homeassistant/.homeassistant/deps/lib/python3.6/site-packages/aiocoap/transports/udp6.py", line 191, in create_client_transport_endpoint
Nov 11 15:15:10 odroid2 hass[5423]:     sock = socket.socket(family=socket.AF_INET6, type=socket.SOCK_DGRAM)
Nov 11 15:15:10 odroid2 hass[5423]:   File "/usr/lib/python3.6/socket.py", line 144, in __init__
Nov 11 15:15:10 odroid2 hass[5423]:     _socket.socket.__init__(self, family, type, proto, fileno)
Nov 11 15:15:10 odroid2 hass[5423]: OSError: [Errno 97] Address family not supported by protocol

Found out that the protocol.py always trying to use udp6 as a transportname in this loop:

        for transportname in defaults.get_default_clienttransports(loop=loop):
            if transportname == 'udp6':
                from .transports.udp6 import TransportEndpointUDP6
                self.transport_endpoints.append((yield from TransportEndpointUDP6.create_client_transport_endpoint(new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop, dump_to=dump_to)))
            elif transportname == 'simple6':
                from .transports.simple6 import TransportEndpointSimple6
                self.transport_endpoints.append((yield from TransportEndpointSimple6.create_client_transport_endpoint(self._dispatch_message, self._dispatch_error, log=self.log, loop=loop)))
                # FIXME warn if dump_to is not None
            elif transportname == 'tinydtls':
                from .transports.tinydtls import TransportEndpointTinyDTLS

                self.transport_endpoints.append((yield from TransportEndpointTinyDTLS.create_client_transport_endpoint(new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop, dump_to=dump_to)))
            else:
                raise RuntimeError("Transport %r not know for client context creation"%transportname)

        return self

**Comment by chrysn** [comment]
CoAP requires some features of the socket API that are rather exotic (sending outgoing requests from the same port as serving incoming requests, using the precise recipient IP addresses to send responses). Those APIs are not very well specified for IPv4, while they have formal specifications for IPv6 (eg. [RFC3542](https://tools.ietf.org/html/rfc3542)).

aiocoap avoids having to support the ill-specified and platform dependent v4 APIs by running all communication through the unified v6mapped interface of the IPv6 APIs, which allows treating IPv4 merely as a particular shape of v6 addresses. The udp6 transport is perfectly capable of working with v4 peers -- it just needs the operating system to support dual stack (or pure v6 :-) ) operation

In this situation, I see several options:
* Rewrite the complete udp6 module on the v4 address stack. I'd accept PRs here if they are well testable and maintained/-able, but personally see no reason to invest any time there.
* Do the same with the simple6 module. It's way easier there (could be just changin family and flags), but is rather [limited](https://aiocoap.readthedocs.io/en/latest/module/aiocoap.transports.simple6.html).
* Solve the actual problem that made you disable ipv6. In many cases, trouble originates from broken routers from your ISP, and the ill-effects of that can be mitigated by telling your network manager (or kernel) to disable IPv6 on that particular interface until whoever broke it fixes it.

**Comment by suppnet** [comment]
Thank you for your detailed response. I wasn't aware of the IPv6 dependecy. The easiest way for me is to enable IPv6, I didn't had any problems with it, just because I didn't have plans to use it I disabled this feature. 
Thanks again for the clarification.

br.
