### ISSUE TITLE
Crash after many requests are sent

### ISSUE THREAD

**Issue by doxxx** [chrysn/aiocoap#152]
I have a long-running Python program using aiocoap on Windows 10 to send PUT requests via UDP to a COAP server once a second. After about 30-35 minutes, the program crashes with the following error:

```
Traceback (most recent call last):
  File ".\testclient.py", line 199, in <module>
    p.print_help()
  File "C:\ProgramData\Anaconda3\Lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\Anaconda3\Lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\Lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\ProgramData\Anaconda3\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\ProgramData\Anaconda3\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```

Increasing the speed at which the requests are sent makes it crash sooner. A similar Node.JS application does not crash.

I'm using a snapshot of aiocoap master at 029a8f0e51f1f2b9c34eb616125b9f772b920b17.

**Comment by chrysn** [comment]
Thanks for the report.

Until there's a fix for it (which would probably mean having a large LRU cache of outgoing connections), you use a workaround: After you've received the first response, store the `.remote` property of the message and set it on the next request message as `.remote` (after having set the URI). When you get any error, you should clear your store and use the next successful request's .remote.

That's an ugly hack but can keep your application going longer, until I get around to properly fixing this.

**Comment by chrysn** [comment]
One note I should probably add here: This affects platforms that use the `simple6` client transport. Platforms that have full support for RFC3542 (and can thus use the `udp6` module) and servers should not be affected.

**Comment by doxxx** [comment]
Thanks, that looks like it has worked.

With regards to fixing it -- perhaps the source UDP port should be bound when the client context is created?

**Comment by chrysn** [comment]
On Thu, Apr 18, 2019 at 07:32:46AM -0700, Gordon Tyler wrote:
> With regards to fixing it -- perhaps the source UDP port should be
> bound when the client context is created?

All that's missing here is a cache of sockets. Currently, the simple6
backend creates a new connected socket for each message rather than
creating a new connected socket for each address. (AFAICT, connected
sockets implicitly get assigned a local address, so binding them
wouldn't do anything if at all possible.)
