### ISSUE TITLE
Drop Python 3.5 (even 3.6?) support

### ISSUE THREAD

**Issue by chrysn** [chrysn/aiocoap#153]
Python 3.6 has introduced some language features I'd like to use (asynchronous generators; variable annotations for better documentation); moreover, the Python 3.5 is a frequent offender in test failure (often due to behaviors of asyncio that have improved in 3.6).

So far I'm keeping Python 3.5 support in as that's what stable Debian ships, but that'll change soon with the release of Buster. There is no concrete release date set for that and neither for dropping 3.5 support in aiocoap, but I'd expect both to happen at some point between May and July.

If you have any deployments where you depend on Python 3.5 support and using the latest aiocoap version, please let me know in this issue.

**Comment by chrysn** [comment]
Who is using Python 3.6 with aiocoap? In my small Debian world, that version doesn't exist (last stable shipped 3.5, current ships 3.7), so dropping 3.6 support right away as well might be an option.

Niceties obtainable with Python 3.7+ are the use of custom module access to make deprecations visible, and better flexibility in type annotations due to deferred evaluation.

(Support for neither will be dropped right-now-next-week, but if you need recent aiocoap versions on <3.7, please let me know).

**Comment by chrysn** [comment]
Python 3.6 is still in Ubuntu LTS (Bionic); until there is a new LTS version, 3.6 will be kept.

**Comment by chrysn** [comment]
With the 7.2 release of PyPy, the concern for PyPy users that depend on 3.5 is out of the way.

**Comment by weili-jiang** [comment]
Hi, we have been using https://github.com/Tanganelli/CoAPthon but are in the process of switching to aiocoap for Python 3 support (and a sane asynchronous model overall). We use OpenEmbedded on ARM targets, as well as Ubuntu LTS.

One of the current versions of OpenEmbedded stable (Thud) is still on Python 3.5. The latest stable (Warrior) is now Python 3.7 but while Thud is still considered stable it would be nice to maintain Python 3.5 support.

**Comment by chrysn** [comment]
The best info I could find on Thud end-of-life is [the yocto release chart](https://wiki.yoctoproject.org/wiki/Releases). That'd put the latest updates to Thud into 2020-04.

I'll try to keep things working on 3.5 until then, but may need to limit the things that are tested in CI. (For example, the DTLS support became unbuildable with the Debian Jessie images I've been using; if you happen to have suggestions for Docker images to run the GitLab CI for 3.5 on, I'd be happy to try moving there).

**Comment by chrysn** [comment]
That 2020-04 date is also anticipated for the next Ubuntu LTS (where the current LTS is keeping 3.6 support in -- I won't keep support for Ubuntu-LTS Python versions for as long as they are supported, as that'd mean having 3.5 around until 2021 and 3.6 until 2023).

That sets the scheduled target version for 2020-04 to 3.7 (i.e. dropping 3.5 and 3.6 support at the same time), as I don't see relevant distribution releases around that'd justify keeping 3.6 in.

**Comment by chrysn** [comment]
I'm starting to phase out support for Python < 3.7, starting with the removal of the CI tests (which have been notoriously failing recently, partially due to their distribution archives being unreachable).

**Comment by weili-jiang** [comment]
We've already moved onto Python 3.7.7 on target, and will be migrating to Ubuntu 20.04 for our development environments shortly, so no concerns from us.

**Comment by chrysn** [comment]
As of [tentatively introducing the ge25519 dependency](https://gitlab.com/aiocoap/aiocoap/-/tree/ge25519-instead-of-nacl), even PyPy was switched to an officially 3.7 version; along with that, 3.6 incompatible changes were done (cda36410eaf6bd1832f03420d554721515de2d61, 85ab45be2768068cb1af5665bcfac53a9f00178d). This cuts the rest of compatibility with 3.7. Some asyncio main loop hacks may still be around that are not yet known to be obsolete, they'll grow out over time.

Thanks for your input on this.
