### ISSUE TITLE
how can i access the coap server without "resouce" path?

### ISSUE THREAD

**Issue by lylening** [chrysn/aiocoap#155]
if i use the code "site.add_resource(["hello"], Resource())", the client should access the coap server by coap://site address/hello. However, some of the iot coap client do not support that. So how can i access the coap server directly by coap://site address, which will also direct to the resource?

**Comment by lylening** [comment]
@chrysn begging for your help

**Comment by chrysn** [comment]
What you are looking for is not "without" a path, but with an empty path:

```python
site.add_resource([], Resource())
```

That resource will be accessible at `coap://site-address` (or `coap://site-address/`, they are equivalent).
