### ISSUE TITLE
"Duplicate NON, ACK or RST received" error when trying to observe multiple resources

### ISSUE THREAD

**Issue by datle1112** [chrysn/aiocoap#165]
Basically i create a function to observe resource (for example resource /3/0/13) and send notification to lwm2m server (coap client) by calling "update_state()" function whenever new data comes:
```
def _notifier(): #function of ObservableResource class
    self.updated_state(response=Encoder.encode())

async def do_notify(model, notifier):
    await asyncio.sleep(2)
    # Update resource /3/0/13
    model.set_resource('3', '0', '13', int(time.time()))
    _notifier()
    # Reschedule itself
    asyncio.create_task(do_notify(model, notifier))

asyncio.create_task(do_notify(model, notifier))
```
However, when i try to create one more function to observe another resource, i got error "Duplicate NON, ACK or RST received" and i don't know how to solve it. Please help me in this problem

**Comment by chrysn** [comment]
I had missed that issue when it was created -- did you need to work around anything in aiocoap, or was something wrong elsewhere?
