### ISSUE TITLE
Stop using SO_REUSEADDRESS

### ISSUE THREAD

**Issue by chrysn** [chrysn/aiocoap#181]
That's going to go away in Python 3.10 for security reasons, and uvloop already dropped support for it.

The udp6 transport already contains a note to do this, but the test suite has not always worked well with that.

**Comment by chrysn** [comment]
Seems it was not that easy, reopening due to https://github.com/chrysn/aiocoap/commit/faa3c1605e54f257116e830457dc2eab2a090f27.

**Comment by chrysn** [comment]
Not only is this happening sooner now ([3.9](https://docs.python.org/3.9/whatsnew/3.9.html)), but also causes trouble on OSX even before that.

Maybe with the new and improved testing procedures, the old fix can pass or at least give better indication of what's needed to improve it.

**Comment by cdh4u** [comment]
I tried with aiocoap 0.4b2, which removes reuse_address=True, and adds reuse_port=True, and now I get the following error on Windows:

ValueError: reuse_port not supported by socket module

So I assume one has to be able to set the port explicitly too.

**Comment by chrysn** [comment]
Thanks, that's valuable input. Explicitly setting the port won't help;
instead, I'll need to auto-detect whether reuse_port is available on the
platform, and just not set it in that case.

(It's not that reuseport/addr is really essential for operation; it just
gives benefits like that you can restart a server faster after an
odd shutdown, and that the server can trivially be scaled up to use
multiple cores. If those are not available on Windows with reuseport
being phased out in Python, and reuseaddr generally unavailable there,
it's more of a nuisance, and hits hard only on high-performance
applications which are often run on Linux servers anyway).

**Comment by chrysn** [comment]
With the 0.4b3 release, autodetection is in place; SO_REUSEADDRESS is used whenever the platform advertises its availability (though that can be overridden using the AIOCOAP_REUSE_PORT environment variable).
