### ISSUE TITLE
Incoming error 111 (connection refused) after EMPTY ACK

### ISSUE THREAD

**Issue by mmajko** [chrysn/aiocoap#200]
I have a client and server code, both using aiocoap for communication. Everything works fine, until the server sends an empty ACK while the response takes too long to prepare.

<img width="1602" alt="Screenshot 2020-06-24 at 23 58 15" src="https://user-images.githubusercontent.com/3010503/85632101-f588c980-b676-11ea-953c-fda5acf29233.png">

The communication gets stuck after the last two messages, the outgoing POST to the server, incoming empty ACK. Notice the first two lines, previous request to the same resource, just without empty ACK, was ok. The only difference is the logic performed based on the incoming message contents, but the resource always sends a response with this line of code:

```python
return aiocoap.Message(code=numbers.codes.Code.CHANGED)
```

After the server sends the empty ACK, it is unable to send another message with the actual response and **Incoming error 111** appears in the server logs (an error logged under DEBUG log level, which is also a bug):

```
DEBUG - Incoming error 111 from <UDP6EndpointAddress [::ffff:10.44.0.26]:46549 with local address>
```

It is suspected, that the client part of aiocoap is actually to blame, because our other coap client written using an different library in C++ is not having such problems, server is able to send the response without any problems and doesn't report the 111 error.

Client code used to reproduce the behavior:

```python
from aiocoap import Context, Message, numbers, optiontypes
import asyncio

baseUrl = 'coap://live'

async def register(client):
    message = Message(code=numbers.codes.Code.POST, uri=baseUrl + '/token/reg', payload=b'AX1')
    message.opt.add_option(optiontypes.UintOption(80, 1))
    response = await client.request(message).response
    return response.payload

async def begin(client, access):
    payload = access + b"\x02\x44\x6c\xdd\x1d\xef\x5c\x93\x08"
    message = Message(code=numbers.codes.Code.POST, uri=baseUrl + '/event', payload=payload)
    response = await client.request(message).response

async def task():
    client = await Context.create_client_context()
    access = await register(client)
    await begin(client, access)

asyncio.run(task())

```

---

Server logs:

```
2020-06-24 21:46:00,440 - CoAPServer - coap-server - DEBUG - Incoming message <aiocoap.Message at 0x7f7c62058460: Type.CON POST (ID 42095, token b'\x00\x00\x92\x0c') remote <UDP6EndpointAddress [::ffff:10.44.0.26]:46549 with local address>, 2 option(s), 12 byte(s) payload>
2020-06-24 21:46:00,441 - CoAPServer - coap-server - DEBUG - New unique message received
2020-06-24 21:46:00,441 - CoAPServer - coap-server.responder - DEBUG - New responder created, key (('event',), <UDP6EndpointAddress [::ffff:10.44.0.26]:46549 with local address>)
2020-06-24 21:46:00,541 - CoAPServer - coap-server.responder - DEBUG - Response preparation takes too long - sending empty ACK.
2020-06-24 21:46:00,542 - CoAPServer - coap-server - DEBUG - Sending message <aiocoap.Message at 0x7f7c620439d0: Type.ACK EMPTY (ID 42095, token b'') remote <UDP6EndpointAddress [::ffff:10.44.0.26]:46549 with local address>>
2020-06-24 21:46:00,861 - CoAPServer - coap-server.responder - DEBUG - Preparing response...
2020-06-24 21:46:00,861 - CoAPServer - coap-server.responder - DEBUG - Sending token: 0000920c
2020-06-24 21:46:00,861 - CoAPServer - coap-server.responder - DEBUG - Sending response, type = Type.CON (request type = Type.CON)
2020-06-24 21:46:00,861 - CoAPServer - coap-server - DEBUG - Sending message <aiocoap.Message at 0x7f7c62f76d00: Type.CON 2.04 Changed (ID 8853, token b'\x00\x00\x92\x0c') remote <UDP6EndpointAddress [::ffff:10.44.0.26]:46549 with local address>>
2020-06-24 21:46:00,861 - CoAPServer - coap-server - DEBUG - Exchange added, message ID: 8853.
2020-06-24 21:46:00,862 - CoAPServer - coap-server - DEBUG - Incoming error 111 from <UDP6EndpointAddress [::ffff:10.44.0.26]:46549 with local address>
```

Client logs:

```
[2020-06-24 21:46:00,444] [DEBUG] [coap] Sending message <aiocoap.Message at 0x7f52d37fa790: Type.CON POST (ID 42095, token b'\x00\x00\x92\x0c') remote <UDP6EndpointAddress [::ffff:xx.xxx.149.187]:5683>, 2 option(s), 12 byte(s) payload>
[2020-06-24 21:46:00,445] [DEBUG] [coap] Exchange added, message ID: 42095.
[2020-06-24 21:46:00,446] [DEBUG] [coap.requester] Timeout is 93.0
[2020-06-24 21:46:00,448] [DEBUG] [coap.requester] Sending request - Token: 0000920c, Remote: <UDP6EndpointAddress [::ffff:xx.xxx.149.187]:5683>
[2020-06-24 21:46:00,596] [DEBUG] [coap] Incoming message <aiocoap.Message at 0x7f52d380dca0: Type.ACK EMPTY (ID 42095, token b'') remote <UDP6EndpointAddress [::ffff:xx.xxx.149.187]:5683 with local address>>
[2020-06-24 21:46:00,596] [DEBUG] [coap] New unique message received
[2020-06-24 21:46:00,598] [DEBUG] [coap] Exchange removed, message ID: 42095.
[2020-06-24 21:47:33,405] [INFO] [coap.requester] Request timed out
```

Note: `python3 -m aiocoap.cli.defaults` doesn't work for me, it gives "No module named aiocoap.cli.defaults" error.

**Comment by chrysn** [comment]
Thanks for reporting this.

Here's what happens in my understanding:

* Client sends request
* Server sends empty ACK
* Server comes up with a response and sends CON
* Server receives an error (111 Connection Refused),
  and consequently stops any attempts to retransmit the CON
* Client waits indefinitely for a response (unless the application times
  out the request), and won't even send concurrent requests as NSTART=1
  limits the outstanding interactions (which is a detail that may or may
  not be implemented with most precision, but the detail doesn't matter
  too much here)

The big question now is where that error comes from. I see two
possibilities:

* It arrives as an ICMP error message -- then we'll have to track down
  whence that comes from.

* It is generated by the kernel as a response to unsuitable transmission
  parameters (like a PKTINFO that's called 'local address' in the logs)
  -- then we'll have to track down what's different between the
  piggy-back responses and the separate one.

As I can't reproduce the error locally without server code to go with it
(somewhat I doubt I could but I'd try; the client code at least looks
insuspicuous), I'd like to ask you to repeat the test with two changes:

* In aiocoap/transport/udp6.py, around the `assert cmsg_level` of line
  461, add a `print("recverr details", cmsg_level, cmsg_type, cmsg_data)`.

* When capturing the network traffic, look for an ICMP error right after
  the empty ACK.

  With the filtering I usually apply (just `coap`), I usually even see
  the ICMP errors, but I don't know how wireshark does that and thus
  whether it's reliable, or what your precise filter settings were --
  please see what you can find. It should arrive right after the ACK, if
  there is any (in the logs it only has 1ms delay).

Oh, just a few more questions for the later interpretation of the above:
Are server and client running on the same host? Can you reproduce this
across different hosts? Does this also occur when you use IPv6?

Ad aiocoap.cli.defaults: That module was only added very recently -- but
speaking of recent, which version of aiocoap are you using? From the
format of the output it appears to be 0.4b1 or earlier. I can't think of
any change between 0.4b1 and 0.4b3 that would fix something like this,
but upgrading would at least help in having a consistent view on the
problem.

**Comment by mmajko** [comment]
Thank you for your quick reply and steps and tips on how to debug this further.

---

>  * It arrives as an ICMP error message -- then we'll have to track down whence that comes from.

Running `tcpdump icmp` on the server side captures a single icmp packet at the time of the error occurrence, saying  
**`udp port 37640 unreachable`**.
```
07:52:01.669858 IP (tos 0xc0, ttl 64, id 27994, offset 0, flags [none], proto ICMP (1), length 62)
    10.44.0.26 > live-567c449946-jnxnz: ICMP 10.44.0.26 udp port 37640 unreachable, length 42
	IP (tos 0x0, ttl 64, id 30307, offset 0, flags [DF], proto UDP (17), length 34)
    live-567c449946-jnxnz.5683 > 10.44.0.26.37640: [bad udp cksum 0x14b9 -> 0x74e9!] UDP, length 6
```
No icmp activity on the client side.

---

> Are server and client running on the same host? Can you reproduce this
across different hosts? Does this also occur when you use IPv6?

Server and client are running on different hosts. Client code runs on my computer, and the server code on a Google Cloud VM.

I am currently forced to use aiocoap in Docker containers, because of #69, and since IPv6 is not supported in Docker containers on macOS I wasn't able to check it for now, but I will try to test the issue on IPv6 in a linux environment later.

---

> In aiocoap/transport/udp6.py, around the `assert cmsg_level` of line 461, add a `print("recverr details", cmsg_level, cmsg_type, cmsg_data)`.

I will provide this later, since it's currently untrivial for us to edit python package contents inside of a docker container (possible on client, much more frustrating to do on server).

---

> ...which version of aiocoap are you using? From the
format of the output it appears to be 0.4b1 or earlier

You've correctly guessed I was running old version (0.3), I've upgraded both server and client to 0.4b3, the problem with error 111 still persists, but here's the promised cli.defaults output for both server and client (I've compared them, they're both identical, which is expected, I'm running them both in containers):

```
Python version: 3.8.2 (default, Apr 23 2020, 14:32:57)
[GCC 8.3.0]
aiocoap version: 0.4b3
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: missing cbor, hkdf, cryptography
    linkheader: everything there
    prettyprint: missing cbor, termcolor, pygments
Python platform: linux
Default server transports:  tcpserver:tcpclient:tlsserver:tlsclient:udp6
Selected server transports: tcpserver:tcpclient:tlsserver:tlsclient:udp6
Default client transports:  tcpclient:tlsclient:udp6
Selected client transports: tcpclient:tlsclient:udp6
SO_REUSEPORT available (default, selected): True, True
```

**Comment by chrysn** [comment]
> Running `tcpdump icmp` on the server side captures a single icmp packet at the time of the error occurrence, saying  
> **`udp port 37640 unreachable`**.
> ```
> 07:52:01.669858 IP (tos 0xc0, ttl 64, id 27994, offset 0, flags [none], proto ICMP (1), length 62)
>     10.44.0.26 > live-567c449946-jnxnz: ICMP 10.44.0.26 udp port 37640 unreachable, length 42
> 	IP (tos 0x0, ttl 64, id 30307, offset 0, flags [DF], proto UDP (17), length 34)
>     live-567c449946-jnxnz.5683 > 10.44.0.26.37640: [bad udp cksum 0x14b9 -> 0x74e9!] UDP, length 6
> ```
> No icmp activity on the client side.

Does 37640 match the port number that the CoAP requests appeared to
come from during that run? (There's at least two layers of NAT involved,
one at your office (192.168...) and one around the server (the
10.44....).

If the ICMP message matches, that would indicate that the stateful
firewall only lets outgoing package through per incoming one -- that
would be really weird, but NATs are weird and cloud hosters even more
so.

It'd be great if you could verify that (eg. by simultaneously capturing
CoAP and ICMP). If possible, storing the dumps along with their logs
"for further interrogation" may be useful, in case more questions come
up.


> I am currently forced to use aiocoap in Docker containers, because of
> #69, and since IPv6 is not supported in Docker containers on macOS I
> wasn't able to check it for now, but I will try to test the issue on
> IPv6 in a linux environment later.

Now that you're on 0.4b3 you may also want to revisit running on macOS
directly. I can't make any promises, but IIRC #69 is primarily waiting
for user confirmation that everything works now.

> > In aiocoap/transport/udp6.py, around the `assert cmsg_level` of line
> > 461, add a `print("recverr details", cmsg_level, cmsg_type,
> > cmsg_data)`.
> 
> I will provide this later, since it's currently untrivial for us to
> edit python package contents inside of a docker container (possible on
> client, much more frustrating to do on server).

If you can run from git-published versions more easily than local
editing, you may want to just run master. I've fixed the lack of debug
information there, so a run from master should tell us a bit more. (Not
that we'd really need that if my NAT hypothesis above is true, but I
kind of hope it's not, because that would plainly make using CoAP in
such cloud hosts impossible).

**Comment by mmajko** [comment]
Sorry for the delay, I got a bit busy.

After a long and exhausting day of debugging I've verified that in fact **it isn't an issue with aiocoap**. I forgot about the most obvious thing sitting in between the client and coap server, and it was **nginx** and the less obvious default configuration of *[ingress-nginx](https://github.com/kubernetes/ingress-nginx)*. The CoAP UDP traffic needs to be proxied through nginx in our case, because of the kubernetes cluster traffic ingress.

The key to resolving the problem was the [`proxy_responses`](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_responses) directive in the *ngx_stream_proxy_module*. It seems that the default value is set to `1` in ingress-nginx configuration, and that caused the connection termination after the first response to the client. After the EMPTY ACK, aiocoap just couldn't connect to the client to send the CON message, session was ended.

It's still question why it stopped with any attempts to retransmit the CON. But that is not exactly relevant to this issue and can be opened as a separate issue.


> Now that you're on 0.4b3 you may also want to revisit running on macOS
directly.

Thank you for this information, you made my life easier. I can confirm it is working on macOS without any apparent problems.

---

Thank you for your support with resolving this issue, it is much appreciated. I'm sorry for any trouble with this misleading issue.

**Comment by chrysn** [comment]
> It's still question why it stopped with any attempts to retransmit the CON. But that is not exactly relevant to this issue and can be opened as a separate issue.

I don't see an open question there -- if a firewall sits between server and client, and that starts issuing ICMP unreachable errors, nothing more can be done. Responsibilities in the protocol are clear (once an empty ACK is there, it's up to the server to do retransmissions, and those are blocked), and it's not CoAP's place to try to circumvent unsuitable firewalls. If there is an issue to open, my view is that it's with whereever ingress-nginx is advertised to be suitable as a generic UDP management tool when it only works for some particular protocols (probably DNS?).

(Don't get me wrong, I'm happy to discuss this further if you disagree -- it just looks quite clear-cut from my PoV right now).
