### ISSUE TITLE
Occasional issue with invalid state with Shelly devices

### ISSUE THREAD

**Issue by chemelli74** [chrysn/aiocoap#210]
From time to time, I see also this error in HA log:

```
2020-09-11 13:33:44 ERROR (MainThread) [coap.blockwise-requester] Exception in BlockwiseRequest runner neither went to response nor to observation: invalid state
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 731, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 860, in _run
    response.set_result(assembled_response)
asyncio.exceptions.InvalidStateError: invalid state

```

As requested, I'll add also the output of python3 -m aiocoap.cli.defaults:

```
Python version: 3.8.4 (default, Aug 24 2020, 15:20:37)
[GCC 9.3.0]
aiocoap version: 0.4b3
Modules missing for subsystems:
    dtls: everything there
    oscore: missing cbor, hkdf
    linkheader: missing LinkHeader
    prettyprint: missing LinkHeader, cbor, termcolor
Python platform: linux
Default server transports:  tinydtls:tcpserver:tcpclient:tlsserver:tlsclient:udp6
Selected server transports: tinydtls:tcpserver:tcpclient:tlsserver:tlsclient:udp6
Default client transports:  tinydtls:tcpclient:tlsclient:udp6
Selected client transports: tinydtls:tcpclient:tlsclient:udp6
SO_REUSEPORT available (default, selected): True, True
```

Thx in advance,

Simone

**Comment by chrysn** [comment]
Hm, that sounds like a request being cancelled right when the last block (or the response, generally) comes in. Do you see any effects in the application that'd indicate that there is someone still waiting for these responses? Does the application have concurrent requests to the same device in the air, or does it sequentially process one ping-pong of requests and responses?

**Comment by chemelli74** [comment]
Actually there are concurrent requests, there will be a check in the future: [Ensure max 1 outstanding request at a time to each device](https://github.com/home-assistant-libs/aioshelly/issues/6)

Simone

**Comment by chemelli74** [comment]
> Actually there are concurrent requests, there will be a check in the future: [Ensure max 1 outstanding request at a time to each device](https://github.com/home-assistant-libs/aioshelly/issues/6)
> 
> Simone

I'm not experiencing this issue any more after updating aioshelly with:

- implementation of a semaphore to avoid concurrent requests.
- implementation of a shared context instead of a context per device

I would say we can close this issue for now; hopefully is completely fixed.
If not I'll open a new one with updated information.

Thx for your support.

Simone

**Comment by chrysn** [comment]
Oh, I've missed your first reply comment, sorry for that.

Only having one aicoap context is generally a good idea (having multiple ones is basically supported, but generally they just make debugging harder).

Under normal circumstances (ie. if there is no tuning of NSTART or similar) and given that shelly devices always send piggybacked responses, the semaphore should not be necessary, as aiocoap already holds the second CON request until the first is ACKed.
