### ISSUE TITLE
aiocoap.cli.rd doesn't seem to handle query correctly

### ISSUE THREAD

**Issue by 2bdkid** [chrysn/aiocoap#218]
I'm trying to understand the CoRE RD RFC and the aiocoap.cli.rd implementation. From looking at aiocoap.cli.rd.py it looks like this query should return the /reg/1 registration, but nothing is returned. I can't find in the RFC where href is a valid query key tho.

```
brady@rpi:~/iot-project3$ aiocoap-client coap://localhost/endpoint-lookup/
</reg/1/>;ep="brady";base="coap://[::1]:5686";rt="core.rd-ep"
brady@rpi:~/iot-project3$ aiocoap-client coap://localhost/endpoint-lookup/?href=coap://[::1]:5686
brady@rpi:~/iot-project3$
```

**Comment by chrysn** [comment]
That query would only yield a result if the registrant actually advertised the root resource -- did it? (A resource lookup would show).

If so, one reason why the query might fail is normalization of the path (`coap://[::1]:5686` is equivalent to `coap://[::1]:5686/` but the implementation doesn't account for that).

What is the information you want to get out of the RD?

**Comment by chrysn** [comment]
There is not an RFC yet, but the [latest published draft mentions](https://tools.ietf.org/html/draft-ietf-core-resource-directory-25#section-6.2) that href is a valid search criterion, and would apply both to the registration resource (ie. you could query `/endpoint-lookup/?href=/reg/1/`) and to registered resources -- but there only to the actually registered resources.

You can also use wildcards to query for `?href=coap://[::1]:5686/*`, but that may make more sense for a resource than for an endpoint lookup.

**Comment by 2bdkid** [comment]
I see what you're saying now. The `href` I needed to query was `href=coap://[::1]:5686/weight`. It did not advertise the root. The goal is to first do something like (but through aiocoap):

```
brady@rpi:~/iot-project3$ aiocoap-client coap://localhost/resource-lookup/?rt=weight
<coap://[::1]:5686/weight>;rt="load weight";obs;anchor="coap://[::1]:5686"
brady@rpi:~/iot-project3$ aiocoap-client coap://localhost/endpoint-lookup/?href=coap://[::1]:5686/weight
</reg/1/>;ep="brady";base="coap://[::1]:5686";rt="core.rd-ep"
```

It would iterate through all the found resources and get their ep.

**Comment by chrysn** [comment]
Just for better understanding (and as I'm still working on the specification and use cases matter): What purpose would you look up the endpoint name for? That direction of lookup has been accepted to be slow so far (having to go through links one by one) because this is a use case that nobody has had so far.

**Comment by 2bdkid** [comment]
The project I'm working on has a UI component to show sensor readings (in my case `/weight` is a digital scale). I was doing to use the ep as a display name within the UI for each sensor. We also considered creating something like a `/id` resource but I was going to figure out the RD queries before we did that. If the ep was returned in the `/resource-lookup/?rt=weight` query it would make it that much easier to get the ep. You would know better than me if that was a good idea or not.

**Comment by chrysn** [comment]
If you can assign names to the individual sensor, you could advertise the sensor as

`</weight>;title="My Bathroom Scale"`

Otherwise (eg. if the title building is complex and you do need more information about the device), your lookup sequence could be

```
$ aiocoap-client coap://localhost/resource-lookup/?rt=weight
<coap://[::1]:5686/weight>;rt="load weight";obs;anchor="coap://[::1]:5686"
$ aiocoap-client coap://localhost/endpoint-lookup/?anchor=coap://[::1]:5686&rel=metadata*
<coap://[::1]:5686/id>;rel=metadata.devicename;anchor="coap://[::1]:5686",
<https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/What%27s_the_Right_Weight_for_My_Height%3F_%284254117120%29.jpg/320px-What%27s_the_Right_Weight_for_My_Height%3F_%284254117120%29.jpg>;rel=metadata.thumbnail;anchor="coap://[::1]:5686"
```

working on the assumption that the metadata resources are descriptive of anything that is hosted at that address.

(Note that I've kept with your style of identifiers; especially for resource types the WIP next draft version will use tag URIs, so it might be more like this:)


```
$ aiocoap-client coap://localhost/resource-lookup/?rt=tag:2bkid.com,2020:weight
<coap://[::1]:5686/weight>;rt="tag:2bkid.com,2020:load tag:2bkid.com,2020:weight";obs;anchor="coap://[::1]:5686"
$ aiocoap-client coap://localhost/endpoint-lookup/?anchor=coap://[::1]:5686&rel=tag:2bkid.com,2020:device.*
<coap://[::1]:5686/id>;rel="tag:2bkid.com,2020:device.name";anchor="coap://[::1]:5686",
<https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/What%27s_the_Right_Weight_for_My_Height%3F_%284254117120%29.jpg/320px-What%27s_the_Right_Weight_for_My_Height%3F_%284254117120%29.jpg>;rel="tag:2bkid.com,2020:device.thumbnail";anchor="coap://[::1]:5686"
```

**Comment by 2bdkid** [comment]
Ah, I see the title is forwarded to the RD. That will work much better, thanks!
