### ISSUE TITLE
DTLS dependency about to break with pip 20.0

### ISSUE THREAD

**Issue by chrysn** [chrysn/aiocoap#219]
CI is giving off messages like:

    DEPRECATION: DTLSSocket was installed using the legacy 'setup.py
    install' method, because a wheel could not be built for it. pip 21.0
    will remove support for this functionality. A possible replacement is
    to fix the wheel build issue reported above. You can find discussion
    regarding this at https://github.com/pypa/pip/issues/8368.

@kabel42, can you do anything there? (I can't open an issue about that upstream as your GitLab instance is unversity-only).

**Comment by kabel42** [comment]
I have a mirror for issues at: https://github.com/kabel42/DTLSSocket

can you reproduce the error directly in DTLSSocket?
`setup.py bdist_wheel` runs fine for me, are you missing the wheel package?

**Comment by chrysn** [comment]
Sorry, forgot that's there. Thanks for the pointer, closing in favor of https://github.com/kabel42/DTLSSocket/issues/2.
