### ISSUE TITLE
PyPI new release

### ISSUE THREAD

**Issue by lord-potato** [chrysn/aiocoap#223]
The PyPI version of aiocoap is very outdated (v0.3), and doesn't support multicast, perhaps it could be updated?

**Comment by chrysn** [comment]
The latest releases are marked as beta on PyPI; unfortunately, that makes them less visible. (In the ["release history" view](https://pypi.org/project/aiocoap/#history), you see the more recent ones.

Even those, though, don't support multicast particularly well on the client side (the application only gets one response); can you tell me a bit about your use case to help shape what's getting added when?

**Comment by lord-potato** [comment]
Thank you! I haven't noticed release history. I'm using multicast for server discovery, with aiocoap being the server, and some openthread devices being the clients. It works flawlessly with 0.4b3
