### ISSUE TITLE
Response from aiocoap-server to request from link local address not possible

### ISSUE THREAD

**Issue by goldroom** [chrysn/aiocoap#234]
A CoAP request is sent from RIOT-OS via 6LoWPAN.
This is the debug output from an aiocoap-server running on a Raspberry Pi 3B+ with an Openlabs 802.15.4 radio module:

```
DEBUG:coap-server:Incoming message <aiocoap.Message at 0x74f19710: Type.NON PUT (MID 49410, token bbd9) remote <UDP6EndpointAddress [fe80::204:2519:1801:ba33%lowpan0] (locally fe80::1%lowpan0)>, 4 option(s), 38 byte(s) payload>
DEBUG:coap-server:New unique message received
DEBUG:coap-server:Sending message <aiocoap.Message at 0x74f19a50: Type.NON 2.01 Created (MID 53985, token bbd9) remote <UDP6EndpointAddress [fe80::204:2519:1801:ba33%lowpan0] (locally fe80::1%lowpan0)>>
DEBUG:coap-server:Socket error recevied, details: SockExtendedErr(ee_errno=113, ee_origin=3, ee_type=1, ee_code=3, ee_pad=0, ee_info=0, ee_data=0)
DEBUG:coap-server:Incoming error 113 from <UDP6EndpointAddress [fe80::204:2519:1801:ba33%lowpan0] (locally fe80::1%lowpan0)>
```

The response isn't captured on `lowpan0` via Wireshark/tcpdump.

___

Python and aiocoap version:
```
python3 -m aiocoap.cli.defaults
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
aiocoap version: 0.4.1
Modules missing for subsystems:
    dtls: everything there
    oscore: everything there
    linkheader: everything there
    prettyprint: everything there
Python platform: linux
Default server transports:  oscore:tinydtls:tcpserver:tcpclient:tlsserver:tlsclient:ws:udp6
Selected server transports: oscore:tinydtls:tcpserver:tcpclient:tlsserver:tlsclient:ws:udp6
Default client transports:  oscore:tinydtls:tcpclient:tlsclient:ws:udp6
Selected client transports: oscore:tinydtls:tcpclient:tlsclient:ws:udp6
SO_REUSEPORT available (default, selected): True, True
```
Kernel version:
`Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux`

Interfaces:
```
ip -6 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fd24:xxxx:xxx::xxx/128 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fd24:xxxx:xxxx:0:xxx:xxx:xxx:xxx/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 6950sec preferred_lft 1550sec
    inet6 fe80::fae5:a3b8:d220:4cad/64 scope link 
       valid_lft forever preferred_lft forever
6: lowpan0@wpan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 state UNKNOWN qlen 1000
    inet6 fe80::1/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by chrysn** [comment]
Phew, I can't reproduce this with what I have here. When I run python 3.7 in a container, the message to the both-sides link-local address can be sent, and just as in your case is annotated with zone identifiers on both ends:

```
DEBUG:coap-server:Sending message <aiocoap.Message at 0x7f18b79b9ed0: Type.ACK 2.05 Content (MID 25603, token 6633) remote <UDP6EndpointAddress [fe80::42:ebff:fe88:c2e5%eth0]:60346 (locally fe80::42:acff:fe11:2%eth0)>, 1 option(s), 197 byte(s) payload>
```

Can you, for comparison, check whether a request to the same server from a different network interface (say, eth0) passes through? (It'd be something like `./aiocoap-client "coap://[fe80::fae5:a3b8:d220:4cad%wifi0]"` from a different computer, with wifi0 being a placeholder for however on the interface is named on that computer).

My worry is that there's something subtly wrong with the device driver for the WPAN device driver -- that'd be pretty hard to detect, and making a workaround trigger only for that case could be quite hard.

**Comment by goldroom** [comment]
It works well by using the link local address of the Rapi's eth0 interface and accessing the CoAP server from a Debian computer.

**Comment by goldroom** [comment]
There was a connection issue between Raspi and SAMR21-xpro via 6LoWPAN. Not an aiocoap issue.

**Comment by chrysn** [comment]
Some of what came together here was influenced by https://github.com/RIOT-Makers/wpan-raspbian/wiki/Link-local-address-fix-for-aiocoap which AFAICT is really outdated. @smlng, can you verify that whichever issues existed back then are long gone (I can't reproduce them but maybe they only showed on a Linux-based BR which I don't have hardware for) and maybe edit the page accordingly (at least pointing out its historical status)?
