### ISSUE TITLE
how to install aiocoap correctly, I installed aiocoap by using pip  but I think it is not the newest version

### ISSUE THREAD

**Issue by FanAndRan** [chrysn/aiocoap#24]
I installed aiocoap by using pip, when I learn it from Usage Examples,
the error happened:

class BlockResource(resource.Resource):
AttributeError: 'module' object has no attribute 'Resource'

Then I check the aiocoap.resource.
The one I installed doesnot has this class, eg:
the aiocoap.resource have three class:
    builtins.object
        CoAPResource
        LinkParam
        Site
It's different from the github version
I execute pip install -U aiocoap
It still doesn't work

my python version : Python 3.4.2
my os: os X Yosemite Version 10.10.2

Thanks in advance!~

------------------------------------------
update:
I uninstalled aiocoap and installed it by using easy_install, but it is the same with before...

**Comment by aellwein** [comment]
Hi @FanAndRan,
i also got this issue, seems that pypi repository contains an oder version of aiocoap.
Please clone the Git repo and use ``python setup.py install --user`` (for user-local installation) or without --user for system-wide installation.

**Comment by FanAndRan** [comment]
hi @aellwein ,
your solution works for me well~ Thank you very much! :D

**Comment by aellwein** [comment]
You are welcome!

**Comment by chrysn** [comment]
thanks for handling this quickly, aellwein, and note to self: this is roughly a duplicate of issue #23
