### ISSUE TITLE
Resource description in the RD saving mechanism 

### ISSUE THREAD

**Issue by Ramzi04** [chrysn/aiocoap#248]
When I run :
`> aiocoap-client --method POST --content-format 40 --payload '</sensors/temp>;rt="temperature-c";' coap://localhost/resourcedirectory/?ep=node1`.

I was wondering how you **save** the resources description in the RD : </sensors/temp>;rt="temperature-c";
Do you use a light database or you save data directly in files ?

**Comment by chrysn** [comment]
The RD's state is, right now, only kept in memory; it is not persisted.

This is considered acceptable here as it's up to the endpoints to
periodically refresh their state anyway, so if the server restarts, the
endpoints are only missing for on average half their registration
lifetime.

Adding a more sophisticated backend is definitely an option, PRs
welcome.

**Comment by Ramzi04** [comment]
Ok @chrysn. Thanks.
