### ISSUE TITLE
Using 'd' attribue in endpoint registration

### ISSUE THREAD

**Issue by Ramzi04** [chrysn/aiocoap#249]
I run :
Step-1: endpoint registration with resources
`aiocoap-client --method POST --content-format 40 --payload '</lamp>;rt="lamp",</light>;rt="sensor"' coap://localhost/resourcedirectory/?ep=lm001&d=bldg1.fl1.off1`
Step-2: endpont lookup with d attribute
`aiocoap-client --method GET  coap://localhost/endpoint-lookup/?d=bldg1*`
I got nothing. Did I miss something to discover EP by sector(domain) attribute in the RD.

**Comment by chrysn** [comment]
That's your shell biting you. Whenever any argument is passed to a
program from a classical UNIX shell, as soon as any funny character is
there whose magic meaning you don't want, quote the argument -- in this
case the registration URI.

The '&' here sends the aiocoap-process to the background; the `d=bl...`
tail of it unfortunately doesn't create any error output that you might
have noticed because it's syntacticallyh a shell variable assignment.

This is not something aiocoap can do anything about; by the time it gets
the argument, it has long been processed by the shell.

**Comment by Ramzi04** [comment]
Thank you so much or the quick response.
Is there any alternative to create an **EP** with its related **sector** 'd'?

**Comment by chrysn** [comment]
> Is there any alternative to create an **EP** with its related **sector** 'd'?

Why use an alternative? Your approach is right, you just need to quote
your commandline argument.

**Comment by Ramzi04** [comment]
Yes, It works perfectly:
`aiocoap-client --method POST --content-format 40 --payload '</lamp>;rt="lamp",</light>;rt="sensor"' 'coap://localhost/resourcedirectory/?ep=lm001&d=bldg1.fl1.off1'`

I need to create the same thing but without aiocoap-client tool.
I run this code:

``` 
async def main():
    
    context = await Context.create_client_context()
    payload = b'</sensors/temp>;rt="temperature-c";if="sensor"' * 30
    request = Message(code=POST, payload=payload, uri="coap://localhost/resourcedirectory/?ep=ep1&d=bldg1.fl1.off1")

    # create the new resource on the directory
    try:
    	response = await context.request(request).response
    	created_uri =  str(response.payload.decode('utf-8'))
    except Exception as e:
    	print(e)
    else:
    	print('Result: %r'%(created_uri))

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

I got this error:
```
ERROR:coap-server:An exception occurred while rendering a resource: AttributeError("'Message' object has no attribute 'request'")
Traceback (most recent call last):
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/protocol.py", line 383, in _render_to_plumbing_request
    await self._render_to_plumbing_request_inner(plumbing_request,
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/protocol.py", line 512, in _render_to_plumbing_request_inner
    response = await self.serversite.render(request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 698, in render
    return await Site.render(self, request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/resource.py", line 369, in render
    return await child.render(subrequest)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/resource.py", line 117, in render
    response = await m(request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 382, in render_post
    links = link_format_from_message(request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 353, in link_format_from_message
    certain_format = message.request.opt.accept
AttributeError: 'Message' object has no attribute 'request'
```

**Comment by Ramzi04** [comment]
Actually, I need to create **hundreds** of resources like that. What is the best method to satisfy this requirement ?
Is it: 
1. using **aiocoap-client** and sh script.
2. using a script python (create_server_context )  like above.
3. Or like server.py example (create_server_context).

**Comment by Ramzi04** [comment]
> I got this error:
> 
> ```
> ERROR:coap-server:An exception occurred while rendering a resource: AttributeError("'Message' object has no attribute 'request'")
> Traceback (most recent call last):
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/protocol.py", line 383, in _render_to_plumbing_request
>     await self._render_to_plumbing_request_inner(plumbing_request,
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/protocol.py", line 512, in _render_to_plumbing_request_inner
>     response = await self.serversite.render(request)
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 698, in render
>     return await Site.render(self, request)
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/resource.py", line 369, in render
>     return await child.render(subrequest)
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/resource.py", line 117, in render
>     response = await m(request)
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 382, in render_post
>     links = link_format_from_message(request)
>   File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 353, in link_format_from_message
>     certain_format = message.request.opt.accept
> AttributeError: 'Message' object has no attribute 'request'
> ```
I forget to specify the content format. The correct code:
```
    context = await Context.create_client_context()
    payload = b'</sensors/temp>;rt="temperature-c";if="sensor"'
    request = Message(code=POST, payload=payload, uri="coap://localhost/resourcedirectory/?ep=ep1")
    request.opt.content_format = 40
```

**Comment by chrysn** [comment]
As for the hundreds, that depends on whether you only need the entries once for testing or for longer testing (including keepalives) or to actually serve the resources. If it's only about creating hundreds once, what you do in #250 looks generally OK.

Is anything else left unresolved from this issue itself?

**Comment by Ramzi04** [comment]
No. Thank you sir.
