### ISSUE TITLE
No response to POST/PUT

### ISSUE THREAD

**Issue by arurke** [chrysn/aiocoap#25]
Hi, this is more a query than an actual issue,

I have a use-case where I send a lot of non-confirmable POST&PUT to my aiocoap server. As described in 5.8.2 and .3 of the standard, the aiocoap server SHOULD send a response - and it does. However, in my case I would like to have the option to not send any responses. I was able to do this using an ugly hack - do you have any suggestion on how I can achieve this gracefully?

Regards,
Andreas U

**Comment by luciotorre** [comment]
From the standard

```When a server is aware that a request arrived via multicast, the
   server MAY always ignore the request, in particular if it doesn't
   have anything useful to respond (e.g., if it only has an empty
   payload or an error response).  The decision for this may depend on
   the application. ```

Maybe this helps. Not that i know how to make aiocoap do this as it will always try to send a response. :)

**Comment by chrysn** [comment]
is it a multicast or a unicast situation this relates to?

for multicast, that's something that is not supported well right now.

for unicast, i'd be rather reluctant to add that unless it is aligned with whatever comes out of draft-tcs-coap-no-response-option. what do you need not sending anything at all for?

**Comment by arurke** [comment]
Hi, I was not aware of the work being done in the draft-tcs-coap-no-response-option. My use-case is unicast and it matches the scenarios described there perfectly. I agree on not adding something until the draft is concluded. I will use my hack for now, which for reference looks like this in protocol.py:991:
```
 # Special case when we don't want the server to reply
if(response.code == DO_NOT_REPLY):
 cancel_thoroughly(delayed_ack)
 self.app_request.cancel()
 return
```
Also added the DO_NOT_REPLY code to code.py

Thx for the reply and link to no-response-option.

**Comment by luciotorre** [comment]
Something like that would be great for me to support multicast with no replies. Would it make sense to add it to aiocoap in lieu of a more complete Multicast support?

**Comment by arurke** [comment]
It seems the draft has concluded in RFC7967
https://tools.ietf.org/html/rfc7967
As of now I have no immediate need for it (need to make client side first), but still curious if you have intentions of adding to aiocoap?

**Comment by chrysn** [comment]
I should maybe have more explicit in the commit message: if you're using the current master, your render method can return the aiocoap.message.NoResponse sentinel.

**Comment by arskanov** [comment]
This is one of the top results when searching for 'aiocoap no-response'.

In case the steps for activating the "no-response" functionality as in RFC7967 in aiocoap are unclear:
- No-response must be set for the response class being generated
- The return message must be of type `NON`

Here's how its set up for me:
```
async def render_post(self, request):
        resp_mtype = request.mtype
        return aiocoap.Message(mtype=resp_mtype)
```

**Comment by chrysn** [comment]
@arskanov, this issue is related to the (long done) introduction of No-Response, which has been changed quite a bit since (cf https://github.com/chrysn/aiocoap/issues/109, 0d09b2eb92a12a01279883f75f1da32099b7559e).

If anything is wrong with no-response in current master, please open a dedicated issue.
