### ISSUE TITLE
autoconf conditional dependency not advertised

### ISSUE THREAD

**Issue by Ramzi04** [chrysn/aiocoap#253]
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
aiocoap version: 0.4.1
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: everything there
    linkheader: everything there
    prettyprint: everything there
Python platform: linux
Default server transports:  oscore:tcpserver:tcpclient:tlsserver:tlsclient:ws:udp6
Selected server transports: oscore:tcpserver:tcpclient:tlsserver:tlsclient:ws:udp6
Default client transports:  oscore:tcpclient:tlsclient:ws:udp6
Selected client transports: oscore:tcpclient:tlsclient:ws:udp6
SO_REUSEPORT available (default, selected): True, True

When I tried to run the following command:
`pip3 install --upgrade "aiocoap[tinydtls]"
`

I got the following error. I guess it has a problem with **DTLSSocket** :

Requirement already up-to-date: aiocoap[tinydtls] in /home/aiocoap/.local/lib/python3.8/site-packages (0.4.1)
Collecting DTLSSocket>=0.1.11a1; extra == "tinydtls"
  Downloading DTLSSocket-0.1.12.tar.gz (150 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Cython
  Using cached Cython-0.29.24-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
Building wheels for collected packages: DTLSSocket
  Building wheel for DTLSSocket (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpxtbu89_e build_wheel /tmp/tmp5sc6pxim
       cwd: /tmp/pip-install-wfihftjo/DTLSSocket
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/DTLSSocket
  copying DTLSSocket/__init__.py -> build/lib.linux-x86_64-3.8/DTLSSocket
  copying DTLSSocket/DTLSSocket.py -> build/lib.linux-x86_64-3.8/DTLSSocket
  running build_ext
  Running: autoconf
  error: [Errno 2] No such file or directory: 'autoconf'
  ERROR: Failed building wheel for DTLSSocket
Failed to build DTLSSocket
ERROR: Could not build wheels for DTLSSocket which use PEP 517 and cannot be installed directly

**Comment by chrysn** [comment]
I'd usually redirect this to the dtlssocket issue tracker, but here the solution is in the output already:

>  Running: autoconf
>  error: [Errno 2] No such file or directory: 'autoconf'

autoconf can be installed as per your operating system's mechanisms.

Leaving this open as a possible documentation improvement issue.

**Comment by Ramzi04** [comment]
Thank you so much @chrysn for the quick reply.
You are right. The problem is related to **autoconf**.
So I just run the following command to install autoconf:
`sudo apt-get install autoconf`

After that you can install tinydtls by running:
`pip3 install --upgrade "aiocoap[tinydtls]"`
