### ISSUE TITLE
Run several nodes servers

### ISSUE THREAD

**Issue by Ramzi04** [chrysn/aiocoap#256]
I tried to run:
```
import logging
import asyncio
import aiocoap
from lightManagerNode import LightSensorResource
logging.basicConfig(level=logging.INFO)
logging.getLogger("coap-server").setLevel(logging.DEBUG)
def main():    
    for indexBuilding in range(0,11):
        for indexFloor in range(1,4):
                for indexOffice in range(0, 11):
                    lightManagerNode = LightSensorResource.createNode()
                    NodePort1 = int("11"+str(indexBuilding)+str(indexFloor)+str(indexOffice))   
                    asyncio.Task(aiocoap.Context.create_server_context(lightManagerNode, ("localhost", NodePort1)))                      
    asyncio.get_event_loop().run_forever()
if __name__ == "__main__":
    main()
```

I got this error:
`
OSError: [Errno 24] Too many open files
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-362' coro=<Context.create_server_context() done, defined at /home/aiocoap/.local/lib/python3.8/site-packages/aiocoap/protocol.py:211> exception=OSError(24, 'Too many open files')>
Traceback (most recent call last):
  File "/home/aiocoap/.local/lib/python3.8/site-packages/aiocoap/protocol.py", line 250, in create_server_context
    await self._append_tokenmanaged_messagemanaged_transport(
  File "/home/aiocoap/.local/lib/python3.8/site-packages/aiocoap/protocol.py", line 147, in _append_tokenmanaged_messagemanaged_transport
    transport = await message_interface_constructor(mman)
  File "/home/aiocoap/.local/lib/python3.8/site-packages/aiocoap/transports/udp6.py", line 332, in create_server_transport_endpoint
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
OSError: [Errno 24] Too many open files
`

Is the limit of Tasks is related to **aiocoap** or it has to do with **Operating System** ?

**Comment by chrysn** [comment]
Each server context creates at least a single socket (possibly more if different transports are enabled).

When hitting this error you're reaching the process's configured limit of how many sockets (or other files) a process can have. I don't have any particular piece of documentation to recommend (it's spread out through POSIX, the shell documentation and operating system specifics), but you may want to look for the terms "ulimit" and the number of allowed file descriptors. What you'll probably wind up running in the end is `ulimit -n unlimited` (but I can't predict whether that'll send you right to other limits).
