### ISSUE TITLE
Randomly "Incoming error 111 from <UDP6EndpointAddress" received and failed

### ISSUE THREAD

**Issue by rxk08011** [chrysn/aiocoap#260]
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0]
aiocoap version: 0.4.1
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: missing cbor2, ge25519
    linkheader: everything there
    prettyprint: missing cbor2
Python platform: linux
Default server transports:  tcpserver:tcpclient:tlsserver:tlsclient:udp6
Selected server transports: tcpserver:tcpclient:tlsserver:tlsclient:udp6
Default client transports:  tcpclient:tlsclient:udp6
Selected client transports: tcpclient:tlsclient:udp6
SO_REUSEPORT available (default, selected): True, True

We have one scenario where randomly get an error "Incoming error 111 from <UDP6EndpointAddress" when we do multiple GET requests. Debug logs are as follow:

DEBUG	Using selector: EpollSelector	
DEBUG	Sending request - Token: 59e9, Remote: <UDP6EndpointAddress 192.168.1.110>	
DEBUG	Sending message <aiocoap.Message at 0x7fd783059c40: Type.CON GET (MID 26022, token 59e9) remote <UDP6EndpointAddress 192.168.1.110>, 1 option(s)>	
DEBUG	Exchange added, message ID: 26022.	
DEBUG	Socket error recevied, details: SockExtendedErr(ee_errno=111, ee_origin=2, ee_type=3, ee_code=3, ee_pad=0, ee_info=0, ee_data=0)	
DEBUG	Incoming error 111 from <UDP6EndpointAddress 192.168.1.110 (locally 192.168.1.51%enp4s0)>

**192.168.1.51 is aiocoap client and 192.168.1.110 is CoAP server.**

We captured traffic in Wireshark and receive an ICMP Destination port unreachable. I have attached pcang file.
[coapcl.zip](https://github.com/chrysn/aiocoap/files/7386880/coapcl.zip)

**Comment by chrysn** [comment]
Closing as the logs indicate that the server is just not running; if you can tell more (see above), please follow up / reopen.
