### ISSUE TITLE
TCP RST Handling

### ISSUE THREAD

**Issue by johnbumgardner** [chrysn/aiocoap#272]
environment
johnbumgardner@Johns-MacBook-Pro-2 HW2 % python3 -m aiocoap.cli.defaults
Python version: 3.8.6 (default, Nov 14 2020, 22:42:03) 
[Clang 12.0.0 (clang-1200.0.32.27)]
aiocoap version: 0.4.3
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: missing cbor2, cryptography, filelock, ge25519
    linkheader: missing LinkHeader
    prettyprint: missing LinkHeader, cbor2, termcolor, pygments
Python platform: darwin
Default server transports:  tcpserver:tcpclient:tlsserver:tlsclient:simple6:simplesocketserver
Selected server transports: tcpserver:tcpclient:tlsserver:tlsclient:simple6:simplesocketserver
Default client transports:  tcpclient:tlsclient:simple6
Selected client transports: tcpclient:tlsclient:simple6
SO_REUSEPORT available (default, selected): True, True

I am running a COAP Server that responds to GET requests. Just interprets the payload and returns text depending on the text.

I am automating a client to send thousands of requests. However, about 10k requests, I get this message, and my client stops running.

Received Type.RST from <aiocoap.transports.simplesocketserver._Address via <aiocoap.transports.simplesocketserver._DatagramServerSocketSimple object at 0x10fd52ee0> to ('192.168.1.54', 50001)>, but could not match it to a running exchange.

Is this something I can watch for?

**Comment by johnbumgardner** [comment]
I went through and tried installing the libraries that arent there. Didnt solve the problem

**Comment by chrysn** [comment]
Are you exchanging these between a single client and server at maximum speed? Are your messages confirlable? If so, why CoAP over UDP? (If both devices can, TCP likely gives you better performanance due to its flow control).

Generally, can you add your code for easier reproduction?

**Comment by johnbumgardner** [comment]
yes it's a single client and single server

here is my server and client code. I wasnt sure how to set tcp programmatically. I set two environment variables
`export AIOCOAP_CLIENT_TRANSPORT="tcpclient"`
`export AIOCOAP_SERVER_TRANSPORT="tcpserver"`

However, after i added this, i got this error message
`raise RuntimeError("No request interface could route message")`
Both devices will support TCP, but I couldnt find any documentation about setting this programmatically. 

```
# coap_server.py
 
import aiocoap.resource as resource
import aiocoap
import asyncio
import socket

class FileResource(resource.Resource):
    def __init__(self):
        super().__init__()
 
    async def render_get(self, request):
        # get file name client wants
        file_name = request.payload

        # open and read the file
        payload = None
        if file_name == b'100B':
            file = open('testfiles/100B', 'rb')
            file_contents = file.read()
        elif file_name == b'10KB':
            file = open('testfiles/10KB', 'rb')
            file_contents = file.read()
        elif file_name == b'1MB':
            file = open('testfiles/1MB', 'rb')
            file_contents = file.read()
        elif file_name == b'10MB':
            file = open('testfiles/10MB', 'rb')
            file_contents = file.read()

        # send client contents of the file    
        return aiocoap.Message(payload=file_contents)
def main():
    # Resource tree creation
    root = resource.Site()
    root.add_resource(['file'], FileResource())
 
    # display server ip
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    print("Server running at ", local_ip)
    asyncio.Task(aiocoap.Context.create_server_context(root, bind=(local_ip, 5683))) 
    asyncio.get_event_loop().run_forever()
 
if __name__ == "__main__":
    main()
```

```
# coap_clientGET.py

import asyncio
import random
import sys
from time import process_time_ns, sleep 
from aiocoap import *

async def make_request(address:str, file:str, iterations:int, debug:bool=False):
    # instantiate a client
    context = await Context.create_client_context()
    
    # create a dictionary to store data
    run_statstics = { 'times' : [], 'num_bytes' : []}
    
    for i in range(iterations):
        # encode desired file name
        payload = bytes(file, 'utf-8')

        # target URI for coap request
        uri = "coap://" + address + "/file"

        # create COAP request
        request = Message(code=GET, payload=payload, uri=uri)

        # get machine start time
        start_time = process_time_ns()

        # asynchronously make request 
        response = await context.request(request).response

        # end clock and compute time the request and transfer took
        end_time = process_time_ns()

        # compute elapsed time in nanoseconds
        elapsed_time = end_time - start_time 

        # compute total size of received COAP response
        bytes_sent = sys.getsizeof(response.code) + sys.getsizeof(response.payload)
        
        # store collected data
        run_statstics['times'].append(elapsed_time)
        run_statstics['num_bytes'].append(bytes_sent)
        
        # debugging
        if debug == True:
            print('---------- run ', i, ' statstics -----------')
            print('elapsed time: ', str(elapsed_time), '(ns)')
            print('length', bytes_sent, ' bytes')
            print('----------')
    return run_statstics   

def coap_file_send(address:str, file:str, iterations:int, debug:bool=False):
    return asyncio.get_event_loop().run_until_complete(make_request(address, file, iterations, debug))

if __name__ == '__main__':
    coap_file_send('localhost', '100B', 10, True)
```


here is my server and client code. I wasnt sure how to set tcp programmatically. I set two environment variables
`export AIOCOAP_CLIENT_TRANSPORT="tcpclient"`
`export AIOCOAP_SERVER_TRANSPORT="tcpserver"`

However, after i added this, i got this error message
`raise RuntimeError("No request interface could route message")`
Both devices will support TCP, but I couldnt find any documentation about setting this programmatically.

**Comment by chrysn** [comment]
Thanks, I'll try to reproduce.

In the meantime, protocol selection happens by scheme, so you just use coap+tcp://hostname in the address, and the rest follows.

**Comment by johnbumgardner** [comment]
I changed the hostname part and resolved the issue. Thank you so much for looking over this bug and helping me resolve it.
