### ISSUE TITLE
ERROR:coap:Connection loss was not expected.

### ISSUE THREAD

**Issue by Sharanabasavaexaleap** [chrysn/aiocoap#285]
Every 5 or 10 seconds i am getting " ERROR:coap:Connection loss was not expected "  from client file with payload. how can i find out the solution to resolve this error.
NOTE: SS is attached belve.
![error connection](https://user-images.githubusercontent.com/95913401/185854999-f1b0e834-d706-4bb9-a41a-a489b75994e5.png)

**Comment by chrysn** [comment]
Please give some more information on what your program does, what the server does, ideally as a minimal example of the issue.

**Comment by Sharanabasavaexaleap** [comment]
HI @chrysn 
![Screenshot from 2022-08-22 12-57-22](https://user-images.githubusercontent.com/95913401/185864061-97f37c7e-11bc-4c28-b501-bb27c1798bd7.png)
 
i am running server,py file in terminal. In Other terminal i am running clientPUT.py file in while loop. above i attached two file and SS please look at once.
![Screenshot from 2022-08-22 12-57-52](https://user-images.githubusercontent.com/95913401/185864035-bdf58978-2c07-4734-b4b5-53616b5d9959.png)
![Screenshot from 2022-08-22 12-57-37](https://user-images.githubusercontent.com/95913401/185864055-ae760b8a-19c0-4892-95ea-54d60a4b8838.png)

**Comment by chrysn** [comment]
I can't do full experimentation right now, but to things probably solve the problem:

* You create a new Context on every loop iteration. There is no need to do that, in all but very exotic cases you only need one single Context, ever.
* If you do have good reasons for having multiple contexts, you should still clean up after them, by running `await context.shutdown()` at the end of your loop. (You could also use the context in an async context manager style, but given that the API for that is not yet ideal, an explicit shutdown probably makes things easier for you).

**Comment by Sharanabasavaexaleap** [comment]
Thanks for your input @chrysn, i will come back with results.

**Comment by Sharanabasavaexaleap** [comment]
> I can't do full experimentation right now, but to things probably solve the problem:
> 
>     * You create a new Context on every loop iteration. There is no need to do that, in all but very exotic cases you only need one single Context, ever.


Hi @chrysn 
"await context.shutdown() at the end of the loop" works for me 
Thanks for the inputs

> 
>     * If you do have good reasons for having multiple contexts, you should still clean up after them, by running `await context.shutdown()` at the end of your loop. (You could also use the context in an async context manager style, but given that the API for that is not yet ideal, an explicit shutdown probably makes things easier for you).

Thnaks @chrysn ,
as your context.shutdown() after the loop

**Comment by chrysn** [comment]
I'm curious: why do you need multiple contexts from a single client in the first place?

**Comment by Sharanabasavaexaleap** [comment]
i am  using proximity sensor in server side(raspberry pi board), for every 5 seconds using client we are receiving detection message.  for this i put it in while loop.

**Comment by chrysn** [comment]
That's fine on its own, but why create a context every time?

I'm particularly curious on the "why", because this happens time and
again, and nobody so far could tell me what led them to do it that way,
and I'd relly like to make documentation better as to avoid that issue
-- but for that I need to understand how this comes to be in the first
place.

**Comment by Sharanabasavaexaleap** [comment]
Sorry @chrysn ,  I got know that  dont need to create context every time(we can create once outside the loop), we can request for payload every time(inside the loop), is this correct or not?

**Comment by chrysn** [comment]
Yes, you create one context outside the loop, and request a payload
every time.

I want to understand: Why did you create multiple contexts? Is the
documentation bad?

**Comment by chrysn** [comment]
As with most Free Software projects, documentation is linked from
the README file:

https://aiocoap.readthedocs.io/
