### ISSUE TITLE
info:coap:Retransmission, Message ID

### ISSUE THREAD

**Issue by Sharanabasavaexaleap** [chrysn/aiocoap#286]
Hi, 
I am running server in one device(rx86) and client in another device(hifive unmatched) while communicating between client and server some time we got "info:coap:Retransmission, Message ID XXXX " and after some time it exit from running. SS show in below. can i know the exact reason for this or is this for slow network?
![Retransmission](https://user-images.githubusercontent.com/95913401/186098567-d0f94260-e044-4aba-b276-7464ed90182e.png)

**Comment by chrysn** [comment]
The answer is likely in the first line -- please give a full log (and copy it to text -- uploaded screenshots of a terminal have terrible accessibility).

As I have a hunch as to where this is coming from[^1], please also provide information about the server you're using. The hardware (hifive) is of little relevance here, what matters is what CoAP software is running there.

[^1]: "My application does not process the responses, even though I see them arrive in a network sniffer. Why is that?" from https://github.com/core-wg/wiki/wiki/CoAP-FAQ

**Comment by chrysn** [comment]
Please tell what resolved your issue.

**Comment by Sharanabasavaexaleap** [comment]
I created context with the name context and protocol , i did not seen that line, now i removed those lines of code still now i did not the error message. i have to see next .

Before
protocol = await Context.create_client_context()
while True:
          context = await Context.create_client_context()
          await asyncio.sleep(1)
          request = Message(code=PUT, payload=b'close_the_door', uri="coap://10.168.1.124/other/block")
          response = await protocol.request(request).response


after:
protocol = await Context.create_client_context()
while True:
          await asyncio.sleep(1)
           request = Message(code=PUT, payload=b'close_the_door', uri="coap://10.168.1.124/other/block")
