### ISSUE TITLE
Handling out of range Block2 requests

### ISSUE THREAD

**Issue by alanc10n** [chrysn/aiocoap#29]
I have a misbehaving client that sometimes continues to request blocks beyond the final block, and I'm hoping to return an error from aiocoap in this case. Currently it misinterprets the first out of range request as a new blockwise request and sends block 0. 

In protocol.py, line 983 (https://github.com/chrysn/aiocoap/blob/master/aiocoap/protocol.py#L983), I see a comment about returning an error when a request with Block2 option and a non-zero block number is processed, but I'm having a hard time figuring out how to implement that. My naive attempt to check for this and return an error at the point in the function where that comment appears doesn't work; quite a few of the unit tests break.

Could you suggest a viable approach to fixing this issue?

Thanks.

**Comment by alanc10n** [comment]
In digging deeper into the test failures, I think it's not the case that I broke a bunch of tests, but rather that something cascaded into breaking multiple tests after a single failure. Running some of the failing tests individually allows them to succeed. I'll investigate further to actually understand the problem and possibly send a pull request when I've sorted out what's going on.

**Comment by alanc10n** [comment]
The change I made is here: https://github.com/alanc10n/aiocoap/commit/0d7e419701d26a39b5c062b14c36e720f84f7209

**Comment by chrysn** [comment]
The underlying problem was that no matter which block was requested first (ie. when no active blockwise transfer was active), the first block was sent in a response. This is fixed in 6fb43530d; sorry this took so long.
