### ISSUE TITLE
udp6

### ISSUE THREAD

**Issue by radkokeves** [chrysn/aiocoap#295]
udp6 is always selected, even when not enabled on host https://github.com/chrysn/aiocoap/blob/5a40b21aa5d00583645b4e617a5f0a30ab129180/aiocoap/defaults.py

**Comment by chrysn** [comment]
The IPv6 stack of modern OSes is capable of also reaching and being reached by legacy IPv4 systems, also when no IPv6 addresses are available. aiocoap uses that interface because that interface is specified more cleanly even for IPv4 traffic.

**Comment by radkokeves** [comment]
thank you very much for clarification (i wasn't aware of that), but it is really confusing, when udp6 is referenced in log files followed by ipv4 address
