### ISSUE TITLE
UDP6 server (acting mostly as a client) occasionally flips which address it initiates traffic from

### ISSUE THREAD

**Issue by roysjosh** [chrysn/aiocoap#298]
For the `aiohomekit` Thread integration, we set up a server context in order to receive pushes from the device but we are otherwise acting as a client. I've finally tracked down sporadic CoAP 4.04 errors the HomeKit accessories are returning. While looking at the Thread traffic, I saw that the (server/sending) IPv6 address suddenly flipped:

![image](https://user-images.githubusercontent.com/601535/208742327-cfc0254a-1c61-4bc5-a8fd-6e88d0653fd2.png)

I feel like this is because I am binding to `::` and maybe some IPv6/kernel interactions (DHCPv6, RA, other black magic) are messing with the routing table to briefly cause another route to take precedence. Here is the steady state:
```plain
# ip -6 r g fde3:a74e:a59f:0:83d9:fe69:fcb4:8fdc
fde3:a74e:a59f:0:83d9:fe69:fcb4:8fdc via fe80::255:daff:fe5f:5147 dev enp1s0  src fd3a:a04c:ba7f::2c7  metric 100
```

I haven't captured anything yet showing a DHCPv6 transaction or RA at the same time as the routes flip... but I want to get advice before I go implement anything crazy. Do you think it makes sense to bind to a specific local IPv6 address to lock communication to that address? Is there something else obvious I'm missing in the code to do that for me?

(@Jc2k for visibility & any input you have)

**Comment by Jc2k** [comment]
So at an ipv6 level, this is a valid thing to happen right? Interfaces with eleventy million different ip addresses is the default now?

If we bind to a specific ip, then we will still get a rogue event generated, but we'll just not see it? So the encryption context will be out, and if we aren't polling (long term goal) then would we miss state? Or are events ACKd?

What would we need to do to actually handle the event?

**Comment by roysjosh** [comment]
Right, the `fd3a:...` address in my case is a DHCPv6 address handed out by my router. `fde3:...` is one of my Thread network prefixes. I've got 3 other addresses on my HA's primary interface.

(Just to clarify - the above screenshot isn't push events, it is the 60s poll from us.)

I think if we pick one address and stick with it, both outgoing 60s poll comms & the incoming push events will all be using the same addresses, versus today where Linux (?) selects whatever address it feels is best. I suspect that all event pushes will work fine as the bulb seems to be tying the session to the original source address. And whenever we don't use that original source address... `4.04`.

**Comment by Jc2k** [comment]
Ok that sounds like a good approach then.

**Comment by roysjosh** [comment]
I'll go ahead and close this as it was more a question of API/usage & it looks like this path works. :tada:
