### ISSUE TITLE
Parse CoAP mesage by bytes

### ISSUE THREAD

**Issue by yooo1999** [chrysn/aiocoap#305]
I have `bytes` that present TCP CoAP message.
Please add that I can use that library to parse that `bytes` to class to I can see the data

**Comment by chrysn** [comment]
This is not a typical use case. You can access the function as `aiocoap.transports.tcp._decode_message`, but it's an internal function.

It's generally possible to make such a function public, but that'd need a good reason: What's the use case?

**Comment by yooo1999** [comment]
I research a device that send CoAP message , but I can't parse it
I tried that function but...
```

File ~/.local/lib/python3.10/site-packages/aiocoap/transports/tcp.py:59, in _decode_message(data)
     55 token = data[tokenoffset:tokenoffset + tkl]
     57 msg = Message(code=code, token=token)
---> 59 msg.payload = msg.opt.decode(data[tokenoffset + tkl:])
     61 return msg

File ~/.local/lib/python3.10/site-packages/aiocoap/options.py:144, in Options.decode(self, rawdata)
    142 rawdata = rawdata[1:]
    143 (delta, rawdata) = _read_extended_field_value(delta, rawdata)
--> 144 (length, rawdata) = _read_extended_field_value(length, rawdata)
    145 option_number += delta
    146 if len(rawdata) < length:

File ~/.local/lib/python3.10/site-packages/aiocoap/options.py:28, in _read_extended_field_value(value, rawdata)
     26     return (int.from_bytes(rawdata[:2], 'big') + 269, rawdata[2:])
     27 else:
---> 28     raise UnparsableMessage("Option contained partial payload marker.")

UnparsableMessage: Option contained partial payload marker.
```

**Comment by chrysn** [comment]
For experimental decoding, the private functions in aiocoap.transports should do fine.

What you're seeing there ... well, the message you're trying to parse is either not a CoAP message at all, or it's not CoAP-over-TCP -- it contains a nibble 0xf in [the delta/length byte of the options encoding](https://www.rfc-editor.org/rfc/rfc7252#section-3.1), which is only allowed if the whole byte is 0xff (the payload marker).

If you can post a nexdump of the message I can try getting you on the right track.
