### ISSUE TITLE
Outdated URL in Readme

### ISSUE THREAD

**Issue by Teufelchen1** [chrysn/aiocoap#345]
This looks pretty offline to me and [others](https://downforeveryoneorjustme.com/coap.technology?proto=http).
https://github.com/chrysn/aiocoap/blob/8508487a1693f8c4c07495f7a27542e6945aff18/README.rst?plain=1#L124

**Comment by chrysn** [comment]
Thanks; had it fixed in other places but not here, fix incoming.
