### ISSUE TITLE
Degraded UX when attempting to interact with non-coap hosts

### ISSUE THREAD

**Issue by Teufelchen1** [chrysn/aiocoap#348]
Hello 🐦 

When running `aiocoap-client coap://[valid_v6%interface]/` against a device that is up and reachable but does *not* run a coap server, the user get the awful error: `Network error: [Errno 111] received through errqueue`. While one can look up the errno number, this is still unnecessary hard and imho a UX failure. 

Expected behaviour:
`The host is up but refuses packets on the coap default port. Are you sure there is a coap server running? Is it on a non default port? (Network error: [Errno 111] received through errqueue)`

**Comment by chrysn** [comment]
Please have a look at #350 for whether that addresses your concerns, would have set the user on the right track, or if there are any enhancements to the messages you'd suggest.
