### ISSUE TITLE
Exception ignored in:

### ISSUE THREAD

**Issue by jdamme** [chrysn/aiocoap#49]
Im using an async post call. I get the correct response but also "Exception ignored in:"

Full debug output:
user@instant-contiki:/git/coap_control$ python3 get3.py 
DEBUG:asyncio:Using selector: EpollSelector
bytearray(b'\x00\x01\x01\xe8\x03')
DEBUG:coap:Sending message <aiocoap.Message at 0xb6c8776c: Type.CON POST (ID 18563, token b'\x00\x00\xa08') remote <UDP6EndpointAddress [fd00:c:1::2]:5683>, 2 option(s), 5 byte(s) payload>
DEBUG:coap:Exchange added, message ID: 18563.
DEBUG:coap.requester:Timeout is 93.0
DEBUG:coap.requester:Sending request - Token: 0000a038, Remote: <UDP6EndpointAddress [fd00:c:1::2]:5683>
DEBUG:coap:Incoming message <aiocoap.Message at 0xb6c8798c: Type.ACK EMPTY (ID 18563, token b'') remote <UDP6EndpointAddress [fd00:c:1::2]:5683 with local address>>
DEBUG:coap:New unique message received
DEBUG:coap:Exchange removed, message ID: 18563.
DEBUG:coap:Incoming message <aiocoap.Message at 0xb6c87c8c: Type.CON 2.05 Content (ID 38725, token b'\x00\x00\xa08') remote <UDP6EndpointAddress [fd00:c:1::2]:5683 with local address>, 5 byte(s) payload>
DEBUG:coap:New unique message received
DEBUG:coap:Received Response: <aiocoap.Message at 0xb6c87c8c: Type.CON 2.05 Content (ID 38725, token b'\x00\x00\xa08') remote <UDP6EndpointAddress [fd00:c:1::2]:5683 with local address>, 5 byte(s) payload>
DEBUG:coap:Sending message <aiocoap.Message at 0xb6c87e6c: Type.ACK EMPTY (ID 38725, token b'') remote <UDP6EndpointAddress [fd00:c:1::2]:5683 with local address>>
Result: 2.05 Content
b'\x00\x01\x00\x01\x00'
Exception ignored in: user@instant-contiki:~/git/coap_control$ 

This is the test program i'm using:

```python
import logging
import asyncio
import struct
from aiocoap import *

logging.basicConfig(level=logging.DEBUG)

node_id = "1"
control_prefix = "fd00:c:"
node_interface_address = "::2"
NodeControlAddress = control_prefix + node_id + node_interface_address

@asyncio.coroutine
def main():
    protocol = yield from Context.create_client_context()

    payload = bytearray()
    payload.append(0)  # connector id
    payload.append(1)  # function id
    payload.append(1)  # num_of_args
    payload.extend(struct.pack("<H", 1000))

    print(repr((payload)))

    request = Message(code=POST, payload=payload, uri='coap://['+NodeControlAddress+']/wishful_funcs')

    try:
        response = yield from protocol.request(request).response
    except Exception as e:
        print('Failed to fetch resource:')
        print(e)
    else:
        print('Result: %s\n%r' % (response.code, response.payload))

if __name__ == "__main__":
     asyncio.get_event_loop().run_until_complete(main())
```

I found this.
http://stackoverflow.com/questions/29502779/aiohttp-exception-ignored-message
So something is still running?

**Comment by jdamme** [comment]
I tried this from what i found online but still got the same problem.

```python
import logging
import asyncio
import struct
from aiocoap import *

logging.basicConfig(level=logging.INFO)

node_id = "1"
control_prefix = "fd00:c:"
node_interface_address = "::2"
NodeControlAddress = control_prefix + node_id + node_interface_address

@asyncio.coroutine
def main():
    protocol = yield from Context.create_client_context()

    payload = bytearray()
    payload.append(0)  # connector id
    payload.append(1)  # function id
    payload.append(1)  # num_of_args
    payload.extend(struct.pack("<H", 1000))

    print(repr((payload)))

    request = Message(code=POST, payload=payload, uri='coap://['+NodeControlAddress+']/wishful_funcs')

    try:
        response = yield from protocol.request(request).response
    except Exception as e:
        print('Failed to fetch resource:')
        print(e)
    else:
        print('Result: %s\n%r' % (response.code, response.payload))

    protocol.shutdown()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    print(asyncio.Task.all_tasks(loop=loop))
    loop.close()
```

**Comment by chrysn** [comment]
hello @jdamme, please retry with the latest master; some bugs have slipped into beginning of this week's master that are now fixed (and are waiting for better unit tests -- see #50 -- for this not to happen again).

**Comment by jdamme** [comment]
Still have the same issue with the updated master code.

**Comment by chrysn** [comment]
Sorry, I could still not reproduce this. Can you provide a (simple, maybe aiocoap) mock for the server's behavior?

**Comment by chrysn** [comment]
Closing this as unreproducible, please feel free to reopen if you can help find a way that others can experiment with the error.
