### ISSUE TITLE
New release on Pypi

### ISSUE THREAD

**Issue by todayispotato** [chrysn/aiocoap#51]
Hello,

Would you mind creating a new release on Pypi? Installing with pip install now gives me version 0.2, which seems to be about a year old.

Regards,
Lars

**Comment by chrysn** [comment]
I'm currently active on a branch for implementing RD and thereby changing some things on the resources side; once that's in a state where I can expect it to have stabilized a little, I'll do a 0.3 release.

Thanks for pointing this out

**Comment by chrysn** [comment]
There is now a 0.3-rc1 release candidate that includes many server-side enhancements from the RD development (without the RD itself as that's not ready for merging into master). I'm expecting some documentation changes before 0.3, but at least now you should be able to get a current aiocoap from pypi.

**Comment by aellwein** [comment]
On a side note, you can get an intermediate artifact directly from GitHub, by putting the following in your ``requirements.txt``:
```
https://github.com/chrysn/aiocoap/archive/0.3-rc1.zip#egg=aiocoap-0.3-rc1
```
And then you can install it with ``pip install -r requirements.txt``.

**Comment by chrysn** [comment]
@aellwein, it's slightly off topic, but as you seem interested in and familiar with those things: i've added installation instructions on https://github.com/chrysn/aiocoap/blob/master/doc/installation.rst , would the `pip install --upgrade git+https` part also work for your use case? (i'd like to keep artifacts like requirements.txt out of the tree as long as they're redundant with setup.py)

**Comment by chrysn** [comment]
a 0.3 is now released.

**Comment by aellwein** [comment]
@chrysn of course, it's ok with me.
