### ISSUE TITLE
Error assembling blockwise response, passing on error NotImplemented()

### ISSUE THREAD

**Issue by GCerar** [chrysn/aiocoap#55]
Reading from `/.well-known/core` on contiki (v2.7) device raises `error.NotImplemented()`. My guess is that something around block2 is not implemented.

    Error assembling blockwise response, passing on error NotImplemented()

    Traceback (most recent call last):
    File "aiocoap_examples.py", line 31, in <module>
        asyncio.get_event_loop().run_until_complete(main())
    File "/usr/lib64/python3.5/asyncio/base_events.py", line 387, in run_until_complete
        return future.result()
    File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
    File "/usr/lib64/python3.5/asyncio/tasks.py", line 241, in _step
        result = coro.throw(exc)
    File "aiocoap_examples.py", line 21, in main
        response = await protocol.request(request).response
    File "/usr/lib64/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
    File "/usr/lib64/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
    File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
    File "/home/gcerar/workspace/logatec2-tools/env35/lib64/python3.5/site-packages/aiocoap/protocol.py", line 742, in process_block2_in_response
        self._assembled_response._append_response_block(response)
    File "/home/gcerar/workspace/logatec2-tools/env35/lib64/python3.5/site-packages/aiocoap/message.py", line 257, in _append_response_block
        raise error.NotImplemented()
    aiocoap.error.NotImplemented

Code where this raises:

    import aiocoap as coap
    import asyncio

    # skipped config of address and port
    async def main():
        uri = 'coap://[{}]:{}/.well-known/core'.format(address, port)

        protocol = await coap.Context.create_client_context()
        request = coap.Message(code=coap.GET, uri=uri)

        try:
            response = await protocol.request(request).response
        except Exception as e:
            print(e)
            raise
        else:
            print('Result: %s\n%r' % (response.code, response.payload))

    if __name__ == '__main__':
        asyncio.get_event_loop().run_until_complete(main())

**Comment by chrysn** [comment]
thanks for reporting this. the easiest way to reproduce this would be
having such a contiki node mapped somewhere in the internet for me to
quickly test that, would that be possible? (you can send the address to
chrysn@fsfe.org if you don't want it to be public).

if that's not an option, could you send network dumps of of the
request/response messages?

**Comment by GCerar** [comment]
Nodes are not in public network. Inside institute I don't have permissions to change that. Security is very tight here. I have sent you on an email tcpdumps of working comm (Firefox's Copper) and non working comm (aiocoap) right before it enters contiki sensor network. Hope it helps.

**Comment by chrysn** [comment]
The problem occurred because one of the early responses in the blockwise
transfer (that had Block2.M=1 set) but did had a payload size different
from the size advertised in Block2.

aiocoap should handle this earlier (when receiving the odd message, not
when receiving the next one), and give a clear error message.

**Comment by GCerar** [comment]
After few exchanged emails with @chrysn, we figured out that issue is on server side. There is a bug at advertising Block2 as @chrysn mentioned. He even gratefully suggested workaround in aiocoap. Until this is fixed, workaround will be kept at my fork, "contiki27-workaround" branch.

Issue can now be closed.

**Comment by chrysn** [comment]
Re-opening because aiocoap did not properly report the issue at the first corrupt message but gave a mislieading error description at a later message.
