### ISSUE TITLE
clientGET-observe constantly sending updates

### ISSUE THREAD

**Issue by Lowell96** [chrysn/aiocoap#59]
Is there any way to code the observe program to only send updates on change. so If I am sending some data to the server every 10 mins or so then I only want it to update then. currently I have edited clientGet-observe.py program so that it gets the temperature topic but it receives and loops through this data constantly even when there has been no update sent. is there anyway to change this. thanks

**Comment by chrysn** [comment]
I'm not sure I really get what you want. If you run clientGET-observer against an external server, it will output a line every time the server sends a new status, independently of whether it changed or not. If you are seeing needless updates here, you could of course make the client display only changes, but really the server should send updates only when either the state changed or considerable time has passed.

Is this issue about the server sending too many updates (is it an aiocoap server / what does it do?), or would you expect the `async for r in request.observation` to only produce results if they are not identical to the previous response?

**Comment by Lowell96** [comment]
Sorry what I meant was is there any way that I can get it to only send a message to the observer when something is PUT on the server topic been observed. almost how MQTT works when it get notifications for the topics it is subscribed to.

**Comment by chrysn** [comment]
The server should currently send a notification exactly when you call a resource's ``.update_state()`` method. Only the ``server.py`` example script sends abundant messages; this is to ease testing (I wouldn't want to wait a minute to see the next update), and you wouldn't do that in real servers.

It also shows that with CoAP observe, you must not rely on there always being a resource state change when you obtain a new value. CoAP observation provides eventual consistency, not an event messaging system.

(As this is already more of a question issue,) What problem do you actually want to solve?

**Comment by chrysn** [comment]
It seems the question is answered, feel free to reopen if there is more.
