### ISSUE TITLE
Allow to omit some options in the client request

### ISSUE THREAD

**Issue by edmont** [chrysn/aiocoap#76]
Sometimes the amount of traffic is critical for a given network, so trying to reduce the packets' size is important. However, the current **aiocoap** implementation does always include the `Uri-Host` and `Uri-Port` options in the requests, which are not always needed. It is possible to set them to _None_ in the [Message](https://github.com/chrysn/aiocoap/blob/master/aiocoap/message.py#L25) class, but a further [check](https://github.com/chrysn/aiocoap/blob/master/aiocoap/cli/client.py#L103) won't allow to send the request.

It would be nice to remove this check.

**Comment by chrysn** [comment]
As the check indicates, you can set the `unresolved_remote` attribute, but the documented way to create such a message is to leave the URI empty initially and then set it using [`set_request_uri`](http://aiocoap.readthedocs.io/en/latest/module/aiocoap.message.html?highlight=uri#aiocoap.message.Message.set_request_uri) with `set_uri_host=False`.
