### ISSUE TITLE
Installation in virtualenv

### ISSUE THREAD

**Issue by eric957** [chrysn/aiocoap#82]
I am beginning to use aiocoap but can't get past the initial step. I may have missed some obvious step.
If there is a forum/mailing list for this kind of issue please tell me.
Here are my sessions (server then client):

~~~
eric@bouleau:/tmp/test$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
eric@bouleau:/tmp/test$ lsb_release -d
Description:    Ubuntu 16.04.3 LTS
eric@bouleau:/tmp/test$ export VENV=$PWD/venv
eric@bouleau:/tmp/test$ python3 -m venv $VENV
eric@bouleau:/tmp/test$ source $VENV/bin/activate
(venv) eric@bouleau:/tmp/test$ pip3 install --upgrade pip
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-9.0.1
(venv) eric@bouleau:/tmp/test$ pip3 install --upgrade "aiocoap[all]"
Collecting aiocoap[all]
  Using cached aiocoap-0.3.tar.gz
  aiocoap 0.3 does not provide the extra 'all'
Installing collected packages: aiocoap
  Running setup.py install for aiocoap ... done
Successfully installed aiocoap-0.3
(venv) eric@bouleau:/tmp/test$ server.py
server.py : commande introuvable
(venv) eric@bouleau:/tmp/test$ python3 $VENV/lib/python3.5/site-packages/tests/server.py
Running test server

eric@bouleau:/tmp/test$ export VENV=$PWD/venv
eric@bouleau:/tmp/test$ source $VENV/bin/activate
(venv) eric@bouleau:/tmp/test$ $VENV/bin/aiocoap-client 'coap://localhost/.well-known/core'
4.04 Not Found
~~~

Neither the server or the client can be run without the full path, contrary to the documentation. Then the client or the server doesn't work as expected. No firewall is configured. Attached is a wireshark capture file with the filter set to interface lo and protocol udp.
[coap.pcap.zip](https://github.com/chrysn/aiocoap/files/1243470/coap.pcap.zip)

Thanks for any hint.

[edited by chrysn for readability]

**Comment by chrysn** [comment]
the complications of running the server stem from the examples not being exported as entry points (unlike aiocoap-client, they are not useful on a general-purpose installation); i should update the documentation to either recommend having a git checkout around, or advertise how to run them.

aiocoap-client should be runnable without path tricks, can you verify that?

as for the .well-know/core, the minimal demo server doesn't export that, i'll fix that. (and moreover, the documentation says that it does -- wishful thinking...)

thanks for your feedback, and let me know if anything was left unclear or you discover more oddities!

**Comment by eric957** [comment]
Yes, aiocoap-client is runnable without the full path.
Thanks for the answers. I'll let you know if there are other issues.
