### ISSUE TITLE
Request storm = Async starvation

### ISSUE THREAD

**Issue by Terris-Dianomic** [chrysn/aiocoap#83]
There appears to be a fundamental problem with async.

When we start sending, say, 300 requests per second to the aiocoap server, the asyncio event queue becomes full of tasks that are eligible for execution, effectively starving other asyncio tasks. For example, there is a task that does some work (that uses async) every 5 seconds. Once a coap request storm hits the process, that task effectively stops running until the storm is over. Under sustained load testing, the task is starved for an infinite amount of time.

I tried running a separate event loop in a different thread for this 5-second task but asyncio doesn't allow two event loops running even in different threads.

Perhaps someone has some ideas as this appears to be about asyncio in general. It would be helpful if aiocoap had a cap on the number of pending/new tasks to add to the event loop but this is just a rough statement.

Here's what I tried: in the handler, a counter is incremented upon entry and decremented upon exit. If the counter hits a maximum, the handler immediately responds with "busy." This, of course, didn't work. This approach establishes a maximum size of the event loop - which is a good effect because the event loop otherwise grows without bound because the handler isn't fast enough to keep up with the load - but other tasks still were starved.

**Comment by chrysn** [comment]
Before I start building a test suite for this: Can you share the tools or setup in which you created the issue?

Am I right assuming that your server handlers all need to actually do asynchronous work? (Otherwise, AFAICT no task switching should occur at all).

Which event loop are you running on? As I understand the UnixSelectorEventLoop, it will always handle pending IO before handling pending timeouts, but I don't know whether aiocoap should try to be smart about this.

**Comment by Terris-Dianomic** [comment]
I'm going to close this. It needs a better explanation with test code. #84 looks promising. 

I am using the default event loop provided by python 3. A storm of coap requests (it could be a ddos attack or just a lot of sensors) can cause the event loop to grow without bound regardless of the counter solution I described above since even the handers (increment a counter and exiting) don't execute fast enough. aiocoap has to ignore incoming requests given some threshold of pending tasks.

What you really need is for me to try this in a multi-node configuration. I currently only have a client box and a server box. There are clearly limitations on this configuration perhaps at the network level.
