### ISSUE TITLE
Work on uvloop

### ISSUE THREAD

**Issue by chrysn** [chrysn/aiocoap#84]
uvloop might be a useful main loop to support (and could address the problems of issues #83 and #73), and was requested in <https://github.com/home-assistant/home-assistant/pull/7815>.

this issue might later be sub-tasked for basic support and testsuite coverage; right now, it describes the whole thing and be used to collect progress data.

**Comment by lwis** [comment]
Current status:

uvloop does not support;
https://github.com/chrysn/aiocoap/blob/47f7de3781605a83956ddfa7b70d0625f1c24085/aiocoap/transports/udp6.py#L142

From looking at the documentation `sock = transport._sock` must be changed into `sock = transport.get_extra_info('socket')`
The get_extra_info method is implemented in uvloop.
https://docs.python.org/3/library/asyncio-protocol.html

However, this appears to result in;

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 191, in _async_setup_component
    result = yield from component.async_setup(hass, processed_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/tradfri.py", line 107, in async_setup
    allow_tradfri_groups))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/tradfri.py", line 121, in _setup_gateway
    api = yield from api_factory(host, key, loop=hass.loop)
  File "/config/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 46, in api_factory
    _protocol = yield from Context.create_client_context(loop=loop)
  File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 524, in create_client_context
    self.transport_endpoints.append((yield from TransportEndpointUDP6.create_client_transport_endpoint(new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop, dump_to=dump_to)))
  File "/usr/lib/python3.6/site-packages/aiocoap/transports/udp6.py", line 179, in create_client_transport_endpoint
    return (yield from cls._create_transport_endpoint(new_message_callback, new_error_callback, log, loop, dump_to, None, multicast=False))
  File "/usr/lib/python3.6/site-packages/aiocoap/transports/udp6.py", line 157, in _create_transport_endpoint
    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
OSError: [Errno 22] Invalid argument
```

**Comment by chrysn** [comment]
funny, i just (as of 20 seconds ago) arrived there too; IMO the next big question is whether uvloop will allow all the recvpktinfo and recvmsg that aiocoap does to support all CoAP situations.

**Comment by chrysn** [comment]
some options i can probably make optional (or find other ways to communicate them to uvloop) like v6only=0 (which should be the default in most situations anyway).

binding (uvloop already binds the socket if no local_addr is given) might need sacrificing older python versions (around 3.4) which could be ok...

**Comment by chrysn** [comment]
some patches down, as i was afraid, the RecvmsgDatagramTransport is a big issue in the way to uvloop compatibility: it is basically a monkey-patch on the builtin asyncio to feed the protocol's `datagram_msg_received` method (with a recvmsg data) rather than its standard `datagram_received`. (should have pushed this upstream harder...)

the good thing is that it'll "just" need an implementation of RecvmsgSelectorDatagramTransport for uvloop. the bad thing is that uvloop's implementation might not be native python...

**Comment by chrysn** [comment]
Progress: The new experimental simple6 transport backend can basically run on uvloop. It is client-only for now and incapable of multicast, but much more portable.

@lwis, could you give it a try? You'd need to run your test server on plain asyncio, but can make aiocoap (for now, expect this mechanism to change) use the simple client implementation by setting the `AIOCOAP_CLIENT_TRANSPORT=simple6` in the environment; then aiocoap should work as long as you only create contexts with `Context.create_client_context()`.

**Comment by chrysn** [comment]
(oh, and it's so far only on the simple6 branch)

**Comment by lwis** [comment]
@chrysn nice work! However, I can't use that branch for testing tradfri as it's missing the dtls functionality.

**Comment by chrysn** [comment]
The simple6 branch is now merged into master and master into tinydtls. The latter is still not really working on uvloop, I'm looking into it.

**Comment by chrysn** [comment]
The remaining issue appears to be that my tinydtls transport implementation is v4-only on uvloop. I'll check whether something from simple6 can be used to mitigate that, or whether the problem is there as well.

**Comment by chrysn** [comment]
uvloop seems to have more issues with IPv6 than the one you originally reported (https://github.com/MagicStack/uvloop/issues/108). With IPv4, I've successfully tested observation; @lwis, can you give it another try? (I suppose you don't need IPv6 anyway, as the Trådfri are 4-only).

**Comment by lwis** [comment]
@chrysn excellent, thanks for the heads up, will test later today!

**Comment by lwis** [comment]
Against latest commit in the tinydtls branch, uvloop 0.8.1, and happens with the `AIOCOAP_CLIENT_TRANSPORT=simple6` set/unset.

Only happens with uvloop installed.

```
hass_1  | decrypt_verify(): found 24 bytes cleartext
hass_1  | decrypt_verify(): found 17 bytes cleartext
hass_1  | Traceback (most recent call last):
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/transports/tinydtls.py", line 212, in _read
hass_1  |     self.coaptransport.new_message_callback(message)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 157, in _dispatch_message
hass_1  |     self._remove_exchange(message)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 284, in _remove_exchange
hass_1  |     cancel_thoroughly(next_retransmission)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/util/asyncio.py", line 19, in cancel_thoroughly
hass_1  |     assert isinstance(handle, asyncio.events.Handle)
hass_1  | AssertionError
hass_1  | Exception ignored in: 'dtls._read'
hass_1  | Traceback (most recent call last):
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/transports/tinydtls.py", line 212, in _read
hass_1  |     self.coaptransport.new_message_callback(message)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 157, in _dispatch_message
hass_1  |     self._remove_exchange(message)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 284, in _remove_exchange
hass_1  |     cancel_thoroughly(next_retransmission)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/util/asyncio.py", line 19, in cancel_thoroughly
hass_1  |     assert isinstance(handle, asyncio.events.Handle)
hass_1  | AssertionError: 
hass_1  | 2017-09-13 17:45:36 WARNING (MainThread) [homeassistant.components.updater] Running on 'dev', only analytics will be submitted
hass_1  | 2017-09-13 17:45:37 WARNING (SyncWorker_6) [pywemo.ssdp] Error fetching description at http://192.168.0.23:13753/devdesc.xml
hass_1  | 2017-09-13 17:45:38 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <function Context._schedule_retransmit.<locals>.retr at 0x7f9910461158>
hass_1  | Traceback (most recent call last):
hass_1  |   File "uvloop/cbhandles.pyx", line 186, in uvloop.loop.TimerHandle._run (uvloop/loop.c:50645)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 331, in retr
hass_1  |     self._retransmit(message, timeout, retransmission_counter)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 338, in _retransmit
hass_1  |     exchange_monitor, next_retransmission = self._active_exchanges.pop(key)
hass_1  | KeyError: (<aiocoap.transports.tinydtls.DTLSClientConnection object at 0x7f9910bc7860>, 60359)
```

**Comment by chrysn** [comment]
On Wed, Sep 13, 2017 at 04:54:11PM +0000, Lewis Juggins wrote:
> Against latest commit in the tinydtls branch, uvloop 0.8.1, and happens with the `AIOCOAP_CLIENT_TRANSPORT=simple6` set/unset.
> 
> Only happens with uvloop installed.

Sure that's latest tinydtls branch of aiocoap? I've removed the
cancel_thoroughly function that raises the AssertionError in c67c2c26
which has been merged into tinydtls.

**Comment by lwis** [comment]
@chrysn you're right, sorry.

Seems to work without the simple6 flag (as expected?)

With;

```
hass_1  | Traceback (most recent call last):
hass_1  |   File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 191, in _async_setup_component
hass_1  |     result = yield from component.async_setup(hass, processed_config)
hass_1  |   File "/usr/lib/python3.6/site-packages/homeassistant/components/tradfri.py", line 107, in async_setup
hass_1  |     allow_tradfri_groups))
hass_1  |   File "/usr/lib/python3.6/site-packages/homeassistant/components/tradfri.py", line 121, in _setup_gateway
hass_1  |     api = yield from api_factory(host, key, loop=hass.loop)
hass_1  |   File "/config/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 160, in api_factory
hass_1  |     yield from request(Command('get', ['status']))
hass_1  |   File "/config/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 125, in request
hass_1  |     result = yield from _execute(api_commands[0])
hass_1  |   File "/config/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 115, in _execute
hass_1  |     _, res = yield from _get_response(msg)
hass_1  |   File "/config/deps/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 77, in _get_response
hass_1  |     r = yield from pr.response
hass_1  |   File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
hass_1  |     yield self  # This tells Task to wait for completion.
hass_1  |   File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
hass_1  |     future.result()
hass_1  |   File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
hass_1  |     raise self._exception
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 796, in _run_outer
hass_1  |     yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 845, in _run
hass_1  |     blockresponse = yield from blockrequest.response
hass_1  |   File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
hass_1  |     yield self  # This tells Task to wait for completion.
hass_1  |   File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
hass_1  |     future.result()
hass_1  |   File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
hass_1  |     raise self._exception
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 675, in _init_phase2
hass_1  |     yield from self.protocol.fill_remote(self.app_request)
hass_1  |   File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 427, in fill_remote
hass_1  |     raise RuntimeError("No transport could route message")
hass_1  | RuntimeError: No transport could route message
```

**Comment by chrysn** [comment]
On Wed, Sep 13, 2017 at 11:22:34AM -0700, Lewis Juggins wrote:
> Seems to work without the simple6 flag (as expected?)
>
> hass_1  | RuntimeError: No transport could route message

Mh, that's a "No transport was configured to deal with coaps://
messages"; I'm afraid I forgot to update the instructions, you'll
probably need AIOCOAP_CLIENT_TRANSPORT=tinydtls:simple6 (or, if you
never use CoAP without DTLS ever at all, =tinydtls).

These things are in motion, but with the current tinydtls branch
(0f09fdf3b), that needs to be set explicitly.

I'm just now working on merging tinydtls into master, at which time it
will auto-detect a sane default for AIOCOAP_CLIENT_TRANSPORT (tinydtls
if DTLSSocket is installed, followed by simple6 or udp6 depending on
platform and used main loop), but that's not finished yet.

**Comment by lwis** [comment]
@chrysn this is good news though, the code appears to be compatible with uvloop for the tradfri use case now. 

I'll update my Home Assistant branch in the mean time.

**Comment by chrysn** [comment]
Update on uvloop support: with the simplesocketserver server side backend that allows running a server with uvloop too, there are two topics left that keep me from announcing uvloop as supported:
* [uvloop's IPv6 issue](https://github.com/MagicStack/uvloop/issues/108) -- the test suite runs everything on IPv6, and while I bent some addresses to run through it on v4 locally (branch tests-v4), I don't want to permanently move the test suite to v4. Let's see whether this can be resolved more easily in uvloop if someone finds out where the v6 issue comes from.
* Some tests don't complete with the simple backends (independent of whether asyncio or uvloop is used), especially the proxy tests are tricky.

Mind you that running on uvloop still means running the simple6/simplesocketserver transports rather than udp6, and there's another [minor issue](https://github.com/MagicStack/uvloop/issues/109) with uvloop, so for example you won't get clean error messages when a port is unreachable, servers need to be bound to a particular address rather than just to `::`, there's no multicast (ok, that's in bad shape in udp6 as well), and things are generally not so well practice-tested yet.

**Comment by chrysn** [comment]
The IPv6 problems have been worked around. The proxying tests that need disabling for the simple6 transport is now independently as https://github.com/chrysn/aiocoap/issues/88.

With uvloop being regularly tested through CI, I'm closing this; thanks @lwis for your interest and help in testing.

**Comment by lwis** [comment]
@chrysn np bud, thanks for taking the time to resolve the issue! 👍  🎉
